// Code generated by mockery v2.53.6. DO NOT EDIT.

package wallet

import (
	context "context"
	domain "go-marketplace/internal/domain"

	decimal "github.com/shopspring/decimal"

	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"

	uuid "github.com/google/uuid"
)

// MockWalletService is an autogenerated mock type for the WalletService type
type MockWalletService struct {
	mock.Mock
}

type MockWalletService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletService) EXPECT() *MockWalletService_Expecter {
	return &MockWalletService_Expecter{mock: &_m.Mock}
}

// AddBalanceTX provides a mock function with given fields: ctx, tx, userID, amount, txData
func (_m *MockWalletService) AddBalanceTX(ctx context.Context, tx *sqlx.Tx, userID uuid.UUID, amount decimal.Decimal, txData domain.WalletTransaction) error {
	ret := _m.Called(ctx, tx, userID, amount, txData)

	if len(ret) == 0 {
		panic("no return value specified for AddBalanceTX")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, decimal.Decimal, domain.WalletTransaction) error); ok {
		r0 = rf(ctx, tx, userID, amount, txData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWalletService_AddBalanceTX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddBalanceTX'
type MockWalletService_AddBalanceTX_Call struct {
	*mock.Call
}

// AddBalanceTX is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - userID uuid.UUID
//   - amount decimal.Decimal
//   - txData domain.WalletTransaction
func (_e *MockWalletService_Expecter) AddBalanceTX(ctx interface{}, tx interface{}, userID interface{}, amount interface{}, txData interface{}) *MockWalletService_AddBalanceTX_Call {
	return &MockWalletService_AddBalanceTX_Call{Call: _e.mock.On("AddBalanceTX", ctx, tx, userID, amount, txData)}
}

func (_c *MockWalletService_AddBalanceTX_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, userID uuid.UUID, amount decimal.Decimal, txData domain.WalletTransaction)) *MockWalletService_AddBalanceTX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID), args[3].(decimal.Decimal), args[4].(domain.WalletTransaction))
	})
	return _c
}

func (_c *MockWalletService_AddBalanceTX_Call) Return(_a0 error) *MockWalletService_AddBalanceTX_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWalletService_AddBalanceTX_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID, decimal.Decimal, domain.WalletTransaction) error) *MockWalletService_AddBalanceTX_Call {
	_c.Call.Return(run)
	return _c
}

// AddPendingBalanceTX provides a mock function with given fields: ctx, tx, userID, amount, txData
func (_m *MockWalletService) AddPendingBalanceTX(ctx context.Context, tx *sqlx.Tx, userID uuid.UUID, amount decimal.Decimal, txData domain.WalletTransaction) error {
	ret := _m.Called(ctx, tx, userID, amount, txData)

	if len(ret) == 0 {
		panic("no return value specified for AddPendingBalanceTX")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, decimal.Decimal, domain.WalletTransaction) error); ok {
		r0 = rf(ctx, tx, userID, amount, txData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWalletService_AddPendingBalanceTX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPendingBalanceTX'
type MockWalletService_AddPendingBalanceTX_Call struct {
	*mock.Call
}

// AddPendingBalanceTX is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - userID uuid.UUID
//   - amount decimal.Decimal
//   - txData domain.WalletTransaction
func (_e *MockWalletService_Expecter) AddPendingBalanceTX(ctx interface{}, tx interface{}, userID interface{}, amount interface{}, txData interface{}) *MockWalletService_AddPendingBalanceTX_Call {
	return &MockWalletService_AddPendingBalanceTX_Call{Call: _e.mock.On("AddPendingBalanceTX", ctx, tx, userID, amount, txData)}
}

func (_c *MockWalletService_AddPendingBalanceTX_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, userID uuid.UUID, amount decimal.Decimal, txData domain.WalletTransaction)) *MockWalletService_AddPendingBalanceTX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID), args[3].(decimal.Decimal), args[4].(domain.WalletTransaction))
	})
	return _c
}

func (_c *MockWalletService_AddPendingBalanceTX_Call) Return(_a0 error) *MockWalletService_AddPendingBalanceTX_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWalletService_AddPendingBalanceTX_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID, decimal.Decimal, domain.WalletTransaction) error) *MockWalletService_AddPendingBalanceTX_Call {
	_c.Call.Return(run)
	return _c
}

// AddPendingBalancesBatchTX provides a mock function with given fields: ctx, tx, userIDs, amounts, txs
func (_m *MockWalletService) AddPendingBalancesBatchTX(ctx context.Context, tx *sqlx.Tx, userIDs []uuid.UUID, amounts []decimal.Decimal, txs []domain.WalletTransaction) error {
	ret := _m.Called(ctx, tx, userIDs, amounts, txs)

	if len(ret) == 0 {
		panic("no return value specified for AddPendingBalancesBatchTX")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, []uuid.UUID, []decimal.Decimal, []domain.WalletTransaction) error); ok {
		r0 = rf(ctx, tx, userIDs, amounts, txs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWalletService_AddPendingBalancesBatchTX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPendingBalancesBatchTX'
type MockWalletService_AddPendingBalancesBatchTX_Call struct {
	*mock.Call
}

// AddPendingBalancesBatchTX is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - userIDs []uuid.UUID
//   - amounts []decimal.Decimal
//   - txs []domain.WalletTransaction
func (_e *MockWalletService_Expecter) AddPendingBalancesBatchTX(ctx interface{}, tx interface{}, userIDs interface{}, amounts interface{}, txs interface{}) *MockWalletService_AddPendingBalancesBatchTX_Call {
	return &MockWalletService_AddPendingBalancesBatchTX_Call{Call: _e.mock.On("AddPendingBalancesBatchTX", ctx, tx, userIDs, amounts, txs)}
}

func (_c *MockWalletService_AddPendingBalancesBatchTX_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, userIDs []uuid.UUID, amounts []decimal.Decimal, txs []domain.WalletTransaction)) *MockWalletService_AddPendingBalancesBatchTX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].([]uuid.UUID), args[3].([]decimal.Decimal), args[4].([]domain.WalletTransaction))
	})
	return _c
}

func (_c *MockWalletService_AddPendingBalancesBatchTX_Call) Return(_a0 error) *MockWalletService_AddPendingBalancesBatchTX_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWalletService_AddPendingBalancesBatchTX_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, []uuid.UUID, []decimal.Decimal, []domain.WalletTransaction) error) *MockWalletService_AddPendingBalancesBatchTX_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWallet provides a mock function with given fields: ctx, userID
func (_m *MockWalletService) CreateWallet(ctx context.Context, userID uuid.UUID) (*WalletResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateWallet")
	}

	var r0 *WalletResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*WalletResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *WalletResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*WalletResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletService_CreateWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWallet'
type MockWalletService_CreateWallet_Call struct {
	*mock.Call
}

// CreateWallet is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockWalletService_Expecter) CreateWallet(ctx interface{}, userID interface{}) *MockWalletService_CreateWallet_Call {
	return &MockWalletService_CreateWallet_Call{Call: _e.mock.On("CreateWallet", ctx, userID)}
}

func (_c *MockWalletService_CreateWallet_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockWalletService_CreateWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockWalletService_CreateWallet_Call) Return(_a0 *WalletResponse, _a1 error) *MockWalletService_CreateWallet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletService_CreateWallet_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*WalletResponse, error)) *MockWalletService_CreateWallet_Call {
	_c.Call.Return(run)
	return _c
}

// DeductBalanceTX provides a mock function with given fields: ctx, tx, userID, amount, txData
func (_m *MockWalletService) DeductBalanceTX(ctx context.Context, tx *sqlx.Tx, userID uuid.UUID, amount decimal.Decimal, txData domain.WalletTransaction) error {
	ret := _m.Called(ctx, tx, userID, amount, txData)

	if len(ret) == 0 {
		panic("no return value specified for DeductBalanceTX")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, decimal.Decimal, domain.WalletTransaction) error); ok {
		r0 = rf(ctx, tx, userID, amount, txData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWalletService_DeductBalanceTX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeductBalanceTX'
type MockWalletService_DeductBalanceTX_Call struct {
	*mock.Call
}

// DeductBalanceTX is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - userID uuid.UUID
//   - amount decimal.Decimal
//   - txData domain.WalletTransaction
func (_e *MockWalletService_Expecter) DeductBalanceTX(ctx interface{}, tx interface{}, userID interface{}, amount interface{}, txData interface{}) *MockWalletService_DeductBalanceTX_Call {
	return &MockWalletService_DeductBalanceTX_Call{Call: _e.mock.On("DeductBalanceTX", ctx, tx, userID, amount, txData)}
}

func (_c *MockWalletService_DeductBalanceTX_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, userID uuid.UUID, amount decimal.Decimal, txData domain.WalletTransaction)) *MockWalletService_DeductBalanceTX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID), args[3].(decimal.Decimal), args[4].(domain.WalletTransaction))
	})
	return _c
}

func (_c *MockWalletService_DeductBalanceTX_Call) Return(_a0 error) *MockWalletService_DeductBalanceTX_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWalletService_DeductBalanceTX_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID, decimal.Decimal, domain.WalletTransaction) error) *MockWalletService_DeductBalanceTX_Call {
	_c.Call.Return(run)
	return _c
}

// FreezeBalanceTX provides a mock function with given fields: ctx, tx, userID, amount, txData
func (_m *MockWalletService) FreezeBalanceTX(ctx context.Context, tx *sqlx.Tx, userID uuid.UUID, amount decimal.Decimal, txData domain.WalletTransaction) error {
	ret := _m.Called(ctx, tx, userID, amount, txData)

	if len(ret) == 0 {
		panic("no return value specified for FreezeBalanceTX")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, decimal.Decimal, domain.WalletTransaction) error); ok {
		r0 = rf(ctx, tx, userID, amount, txData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWalletService_FreezeBalanceTX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FreezeBalanceTX'
type MockWalletService_FreezeBalanceTX_Call struct {
	*mock.Call
}

// FreezeBalanceTX is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - userID uuid.UUID
//   - amount decimal.Decimal
//   - txData domain.WalletTransaction
func (_e *MockWalletService_Expecter) FreezeBalanceTX(ctx interface{}, tx interface{}, userID interface{}, amount interface{}, txData interface{}) *MockWalletService_FreezeBalanceTX_Call {
	return &MockWalletService_FreezeBalanceTX_Call{Call: _e.mock.On("FreezeBalanceTX", ctx, tx, userID, amount, txData)}
}

func (_c *MockWalletService_FreezeBalanceTX_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, userID uuid.UUID, amount decimal.Decimal, txData domain.WalletTransaction)) *MockWalletService_FreezeBalanceTX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID), args[3].(decimal.Decimal), args[4].(domain.WalletTransaction))
	})
	return _c
}

func (_c *MockWalletService_FreezeBalanceTX_Call) Return(_a0 error) *MockWalletService_FreezeBalanceTX_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWalletService_FreezeBalanceTX_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID, decimal.Decimal, domain.WalletTransaction) error) *MockWalletService_FreezeBalanceTX_Call {
	_c.Call.Return(run)
	return _c
}

// GetWalletByUserID provides a mock function with given fields: ctx, userID
func (_m *MockWalletService) GetWalletByUserID(ctx context.Context, userID uuid.UUID) (*WalletResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWalletByUserID")
	}

	var r0 *WalletResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*WalletResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *WalletResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*WalletResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletService_GetWalletByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWalletByUserID'
type MockWalletService_GetWalletByUserID_Call struct {
	*mock.Call
}

// GetWalletByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockWalletService_Expecter) GetWalletByUserID(ctx interface{}, userID interface{}) *MockWalletService_GetWalletByUserID_Call {
	return &MockWalletService_GetWalletByUserID_Call{Call: _e.mock.On("GetWalletByUserID", ctx, userID)}
}

func (_c *MockWalletService_GetWalletByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockWalletService_GetWalletByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockWalletService_GetWalletByUserID_Call) Return(_a0 *WalletResponse, _a1 error) *MockWalletService_GetWalletByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletService_GetWalletByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*WalletResponse, error)) *MockWalletService_GetWalletByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetWalletHistory provides a mock function with given fields: ctx, userID, page, limit
func (_m *MockWalletService) GetWalletHistory(ctx context.Context, userID uuid.UUID, page int, limit int) ([]TransactionResponse, error) {
	ret := _m.Called(ctx, userID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetWalletHistory")
	}

	var r0 []TransactionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]TransactionResponse, error)); ok {
		return rf(ctx, userID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []TransactionResponse); ok {
		r0 = rf(ctx, userID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]TransactionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, userID, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletService_GetWalletHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWalletHistory'
type MockWalletService_GetWalletHistory_Call struct {
	*mock.Call
}

// GetWalletHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - page int
//   - limit int
func (_e *MockWalletService_Expecter) GetWalletHistory(ctx interface{}, userID interface{}, page interface{}, limit interface{}) *MockWalletService_GetWalletHistory_Call {
	return &MockWalletService_GetWalletHistory_Call{Call: _e.mock.On("GetWalletHistory", ctx, userID, page, limit)}
}

func (_c *MockWalletService_GetWalletHistory_Call) Run(run func(ctx context.Context, userID uuid.UUID, page int, limit int)) *MockWalletService_GetWalletHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockWalletService_GetWalletHistory_Call) Return(_a0 []TransactionResponse, _a1 error) *MockWalletService_GetWalletHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletService_GetWalletHistory_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]TransactionResponse, error)) *MockWalletService_GetWalletHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetWalletsByUserIDs provides a mock function with given fields: ctx, userIDs
func (_m *MockWalletService) GetWalletsByUserIDs(ctx context.Context, userIDs []uuid.UUID) ([]WalletResponse, error) {
	ret := _m.Called(ctx, userIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetWalletsByUserIDs")
	}

	var r0 []WalletResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]WalletResponse, error)); ok {
		return rf(ctx, userIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []WalletResponse); ok {
		r0 = rf(ctx, userIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]WalletResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, userIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletService_GetWalletsByUserIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWalletsByUserIDs'
type MockWalletService_GetWalletsByUserIDs_Call struct {
	*mock.Call
}

// GetWalletsByUserIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userIDs []uuid.UUID
func (_e *MockWalletService_Expecter) GetWalletsByUserIDs(ctx interface{}, userIDs interface{}) *MockWalletService_GetWalletsByUserIDs_Call {
	return &MockWalletService_GetWalletsByUserIDs_Call{Call: _e.mock.On("GetWalletsByUserIDs", ctx, userIDs)}
}

func (_c *MockWalletService_GetWalletsByUserIDs_Call) Run(run func(ctx context.Context, userIDs []uuid.UUID)) *MockWalletService_GetWalletsByUserIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *MockWalletService_GetWalletsByUserIDs_Call) Return(_a0 []WalletResponse, _a1 error) *MockWalletService_GetWalletsByUserIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletService_GetWalletsByUserIDs_Call) RunAndReturn(run func(context.Context, []uuid.UUID) ([]WalletResponse, error)) *MockWalletService_GetWalletsByUserIDs_Call {
	_c.Call.Return(run)
	return _c
}

// RefundFromPendingTX provides a mock function with given fields: ctx, tx, userID, amount, txData
func (_m *MockWalletService) RefundFromPendingTX(ctx context.Context, tx *sqlx.Tx, userID uuid.UUID, amount decimal.Decimal, txData domain.WalletTransaction) error {
	ret := _m.Called(ctx, tx, userID, amount, txData)

	if len(ret) == 0 {
		panic("no return value specified for RefundFromPendingTX")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, decimal.Decimal, domain.WalletTransaction) error); ok {
		r0 = rf(ctx, tx, userID, amount, txData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWalletService_RefundFromPendingTX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefundFromPendingTX'
type MockWalletService_RefundFromPendingTX_Call struct {
	*mock.Call
}

// RefundFromPendingTX is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - userID uuid.UUID
//   - amount decimal.Decimal
//   - txData domain.WalletTransaction
func (_e *MockWalletService_Expecter) RefundFromPendingTX(ctx interface{}, tx interface{}, userID interface{}, amount interface{}, txData interface{}) *MockWalletService_RefundFromPendingTX_Call {
	return &MockWalletService_RefundFromPendingTX_Call{Call: _e.mock.On("RefundFromPendingTX", ctx, tx, userID, amount, txData)}
}

func (_c *MockWalletService_RefundFromPendingTX_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, userID uuid.UUID, amount decimal.Decimal, txData domain.WalletTransaction)) *MockWalletService_RefundFromPendingTX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID), args[3].(decimal.Decimal), args[4].(domain.WalletTransaction))
	})
	return _c
}

func (_c *MockWalletService_RefundFromPendingTX_Call) Return(_a0 error) *MockWalletService_RefundFromPendingTX_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWalletService_RefundFromPendingTX_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID, decimal.Decimal, domain.WalletTransaction) error) *MockWalletService_RefundFromPendingTX_Call {
	_c.Call.Return(run)
	return _c
}

// SettlePendingBalanceTX provides a mock function with given fields: ctx, tx, userID, amount, txData
func (_m *MockWalletService) SettlePendingBalanceTX(ctx context.Context, tx *sqlx.Tx, userID uuid.UUID, amount decimal.Decimal, txData domain.WalletTransaction) error {
	ret := _m.Called(ctx, tx, userID, amount, txData)

	if len(ret) == 0 {
		panic("no return value specified for SettlePendingBalanceTX")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, decimal.Decimal, domain.WalletTransaction) error); ok {
		r0 = rf(ctx, tx, userID, amount, txData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWalletService_SettlePendingBalanceTX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SettlePendingBalanceTX'
type MockWalletService_SettlePendingBalanceTX_Call struct {
	*mock.Call
}

// SettlePendingBalanceTX is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - userID uuid.UUID
//   - amount decimal.Decimal
//   - txData domain.WalletTransaction
func (_e *MockWalletService_Expecter) SettlePendingBalanceTX(ctx interface{}, tx interface{}, userID interface{}, amount interface{}, txData interface{}) *MockWalletService_SettlePendingBalanceTX_Call {
	return &MockWalletService_SettlePendingBalanceTX_Call{Call: _e.mock.On("SettlePendingBalanceTX", ctx, tx, userID, amount, txData)}
}

func (_c *MockWalletService_SettlePendingBalanceTX_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, userID uuid.UUID, amount decimal.Decimal, txData domain.WalletTransaction)) *MockWalletService_SettlePendingBalanceTX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID), args[3].(decimal.Decimal), args[4].(domain.WalletTransaction))
	})
	return _c
}

func (_c *MockWalletService_SettlePendingBalanceTX_Call) Return(_a0 error) *MockWalletService_SettlePendingBalanceTX_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWalletService_SettlePendingBalanceTX_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID, decimal.Decimal, domain.WalletTransaction) error) *MockWalletService_SettlePendingBalanceTX_Call {
	_c.Call.Return(run)
	return _c
}

// Withdraw provides a mock function with given fields: ctx, userID, req
func (_m *MockWalletService) Withdraw(ctx context.Context, userID uuid.UUID, req WithdrawRequest) error {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, WithdrawRequest) error); ok {
		r0 = rf(ctx, userID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWalletService_Withdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdraw'
type MockWalletService_Withdraw_Call struct {
	*mock.Call
}

// Withdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req WithdrawRequest
func (_e *MockWalletService_Expecter) Withdraw(ctx interface{}, userID interface{}, req interface{}) *MockWalletService_Withdraw_Call {
	return &MockWalletService_Withdraw_Call{Call: _e.mock.On("Withdraw", ctx, userID, req)}
}

func (_c *MockWalletService_Withdraw_Call) Run(run func(ctx context.Context, userID uuid.UUID, req WithdrawRequest)) *MockWalletService_Withdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(WithdrawRequest))
	})
	return _c
}

func (_c *MockWalletService_Withdraw_Call) Return(_a0 error) *MockWalletService_Withdraw_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWalletService_Withdraw_Call) RunAndReturn(run func(context.Context, uuid.UUID, WithdrawRequest) error) *MockWalletService_Withdraw_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWalletService creates a new instance of MockWalletService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletService {
	mock := &MockWalletService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
