// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "go-shop-yourself/internal/dtos"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AuthServiceInterface is an autogenerated mock type for the AuthServiceInterface type
type AuthServiceInterface struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, email, password
func (_m *AuthServiceInterface) Login(ctx context.Context, email string, password string) (*dtos.AuthResponse, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *dtos.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*dtos.AuthResponse, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *dtos.AuthResponse); ok {
		r0 = rf(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Logout provides a mock function with given fields: ctx, rawToken
func (_m *AuthServiceInterface) Logout(ctx context.Context, rawToken string) error {
	ret := _m.Called(ctx, rawToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, rawToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshTokens provides a mock function with given fields: ctx, rawToken
func (_m *AuthServiceInterface) RefreshTokens(ctx context.Context, rawToken string) (*dtos.AuthResponse, error) {
	ret := _m.Called(ctx, rawToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshTokens")
	}

	var r0 *dtos.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dtos.AuthResponse, error)); ok {
		return rf(ctx, rawToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dtos.AuthResponse); ok {
		r0 = rf(ctx, rawToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, rawToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, email, password, username
func (_m *AuthServiceInterface) Register(ctx context.Context, email string, password string, username string) (uuid.UUID, error) {
	ret := _m.Called(ctx, email, password, username)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (uuid.UUID, error)); ok {
		return rf(ctx, email, password, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) uuid.UUID); ok {
		r0 = rf(ctx, email, password, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, email, password, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthServiceInterface creates a new instance of AuthServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthServiceInterface {
	mock := &AuthServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
