// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "go-shop-yourself/internal/dtos"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MerchantServiceInterface is an autogenerated mock type for the MerchantServiceInterface type
type MerchantServiceInterface struct {
	mock.Mock
}

// RegisterMerchant provides a mock function with given fields: ctx, userID, req
func (_m *MerchantServiceInterface) RegisterMerchant(ctx context.Context, userID uuid.UUID, req dtos.MerchantRegisterRequest) (*dtos.MerchantResponse, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for RegisterMerchant")
	}

	var r0 *dtos.MerchantResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dtos.MerchantRegisterRequest) (*dtos.MerchantResponse, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dtos.MerchantRegisterRequest) *dtos.MerchantResponse); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.MerchantResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, dtos.MerchantRegisterRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMerchantServiceInterface creates a new instance of MerchantServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMerchantServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MerchantServiceInterface {
	mock := &MerchantServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
