// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "go-shop-yourself/internal/dtos"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ProductServiceInterface is an autogenerated mock type for the ProductServiceInterface type
type ProductServiceInterface struct {
	mock.Mock
}

// CreateProduct provides a mock function with given fields: ctx, req
func (_m *ProductServiceInterface) CreateProduct(ctx context.Context, req dtos.ProductCreateRequest) (*dtos.ProductResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 *dtos.ProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dtos.ProductCreateRequest) (*dtos.ProductResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dtos.ProductCreateRequest) *dtos.ProductResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.ProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dtos.ProductCreateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProduct provides a mock function with given fields: ctx, id, req
func (_m *ProductServiceInterface) UpdateProduct(ctx context.Context, id uuid.UUID, req dtos.ProductUpdateRequest) (*dtos.ProductResponse, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProduct")
	}

	var r0 *dtos.ProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dtos.ProductUpdateRequest) (*dtos.ProductResponse, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dtos.ProductUpdateRequest) *dtos.ProductResponse); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.ProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, dtos.ProductUpdateRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProductServiceInterface creates a new instance of ProductServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductServiceInterface {
	mock := &ProductServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
