// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "go-shop-yourself/internal/domain"

	decimal "github.com/shopspring/decimal"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"

	uuid "github.com/google/uuid"
)

// WalletRepository is an autogenerated mock type for the WalletRepository type
type WalletRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, w
func (_m *WalletRepository) Create(ctx context.Context, w *domain.Wallet) error {
	ret := _m.Called(ctx, w)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Wallet) error); ok {
		r0 = rf(ctx, w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTx provides a mock function with given fields: ctx, tx, w
func (_m *WalletRepository) CreateTx(ctx context.Context, tx pgx.Tx, w *domain.Wallet) error {
	ret := _m.Called(ctx, tx, w)

	if len(ret) == 0 {
		panic("no return value specified for CreateTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, *domain.Wallet) error); ok {
		r0 = rf(ctx, tx, w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPool provides a mock function with no fields
func (_m *WalletRepository) GetPool() domain.Pool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPool")
	}

	var r0 domain.Pool
	if rf, ok := ret.Get(0).(func() domain.Pool); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Pool)
		}
	}

	return r0
}

// GetWalletByUserID provides a mock function with given fields: ctx, userID
func (_m *WalletRepository) GetWalletByUserID(ctx context.Context, userID uuid.UUID) (*domain.Wallet, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWalletByUserID")
	}

	var r0 *domain.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Wallet, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Wallet); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWalletHistory provides a mock function with given fields: ctx, walletID, limit, offset
func (_m *WalletRepository) GetWalletHistory(ctx context.Context, walletID uuid.UUID, limit int, offset int) ([]domain.WalletTransaction, error) {
	ret := _m.Called(ctx, walletID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetWalletHistory")
	}

	var r0 []domain.WalletTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]domain.WalletTransaction, error)); ok {
		return rf(ctx, walletID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []domain.WalletTransaction); ok {
		r0 = rf(ctx, walletID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.WalletTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, walletID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Withdraw provides a mock function with given fields: ctx, walletID, amount, txData
func (_m *WalletRepository) Withdraw(ctx context.Context, walletID uuid.UUID, amount decimal.Decimal, txData domain.WalletTransaction) error {
	ret := _m.Called(ctx, walletID, amount, txData)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, decimal.Decimal, domain.WalletTransaction) error); ok {
		r0 = rf(ctx, walletID, amount, txData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWalletRepository creates a new instance of WalletRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWalletRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WalletRepository {
	mock := &WalletRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
