with-expecter: true
recursive: true
all: true
inpackage: true
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
filename: "mock_{{.InterfaceName}}.go"
packages:
  go-marketplace/internal/user:
    interfaces:
      UserRepository:
      UserServiceInterface:
  go-marketplace/internal/auth:
    interfaces:
      AuthServiceInterface:
      RefreshTokenRepository:
      SupabaseAuthClient:
  go-marketplace/internal/merchant:
    interfaces:
      MerchantServiceInterface:
      MerchantRepository:
  go-marketplace/internal/product:
    interfaces:
      ProductServiceInterface:
      ProductRepository:
  go-marketplace/internal/wallet:
    interfaces:
      WalletServiceInterface:
      WalletRepository:
  go-marketplace/internal/cart:
    interfaces:
      CartServiceInterface:
      CartRepository:
  go-marketplace/internal/order:
    interfaces:
      OrderServiceInterface:
      OrderRepository:
  go-marketplace/internal/domain:
    interfaces:
      Pool:
