with-expecter: true
recursive: true
all: true
inpackage: true
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
filename: "mock_{{.InterfaceName}}.go"
packages:
  go-marketplace/internal/core/user:
    interfaces:
      UserRepository:
      UserServiceInterface:
  go-marketplace/internal/core/auth:
    interfaces:
      AuthServiceInterface:
      SessionRepository:
      VerificationRepository:
      MailServiceInterface:
  go-marketplace/internal/core/merchant:
    interfaces:
      MerchantServiceInterface:
      MerchantRepository:
  go-marketplace/internal/core/product:
    interfaces:
      ProductServiceInterface:
      ProductRepository:
  go-marketplace/internal/core/wallet:
    interfaces:
      WalletServiceInterface:
      WalletRepository:
  go-marketplace/internal/core/cart:
    interfaces:
      CartServiceInterface:
      CartRepository:
  go-marketplace/internal/core/order:
    interfaces:
      OrderServiceInterface:
      OrderRepository:
  go-marketplace/internal/core/payment:
    interfaces:
      PaymentServiceInterface:
      PaymentRepository:
  go-marketplace/internal/domain:
    interfaces:
      Pool:
