with-expecter: true
recursive: true
all: true
inpackage: true
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
filename: "mock_{{.InterfaceName}}.go"
packages:
  go-shop-yourself/internal/user:
    interfaces:
      UserRepository:
      UserServiceInterface:
  go-shop-yourself/internal/auth:
    interfaces:
      AuthServiceInterface:
      RefreshTokenRepository:
  go-shop-yourself/internal/merchant:
    interfaces:
      MerchantServiceInterface:
      MerchantRepository:
  go-shop-yourself/internal/product:
    interfaces:
      ProductServiceInterface:
      ProductRepository:
  go-shop-yourself/internal/wallet:
    interfaces:
      WalletServiceInterface:
      WalletRepository:
  go-shop-yourself/internal/domain:
    interfaces:
      Pool:
