// Code generated by mockery v2.53.6. DO NOT EDIT.

package payment

import (
	context "context"
	domain "go-marketplace/internal/domain"

	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"

	uuid "github.com/google/uuid"
)

// MockPaymentRepository is an autogenerated mock type for the PaymentRepository type
type MockPaymentRepository struct {
	mock.Mock
}

type MockPaymentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentRepository) EXPECT() *MockPaymentRepository_Expecter {
	return &MockPaymentRepository_Expecter{mock: &_m.Mock}
}

// CreateDistributionTX provides a mock function with given fields: ctx, tx, d
func (_m *MockPaymentRepository) CreateDistributionTX(ctx context.Context, tx *sqlx.Tx, d *domain.PaymentDistribution) error {
	ret := _m.Called(ctx, tx, d)

	if len(ret) == 0 {
		panic("no return value specified for CreateDistributionTX")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *domain.PaymentDistribution) error); ok {
		r0 = rf(ctx, tx, d)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentRepository_CreateDistributionTX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDistributionTX'
type MockPaymentRepository_CreateDistributionTX_Call struct {
	*mock.Call
}

// CreateDistributionTX is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - d *domain.PaymentDistribution
func (_e *MockPaymentRepository_Expecter) CreateDistributionTX(ctx interface{}, tx interface{}, d interface{}) *MockPaymentRepository_CreateDistributionTX_Call {
	return &MockPaymentRepository_CreateDistributionTX_Call{Call: _e.mock.On("CreateDistributionTX", ctx, tx, d)}
}

func (_c *MockPaymentRepository_CreateDistributionTX_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, d *domain.PaymentDistribution)) *MockPaymentRepository_CreateDistributionTX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(*domain.PaymentDistribution))
	})
	return _c
}

func (_c *MockPaymentRepository_CreateDistributionTX_Call) Return(_a0 error) *MockPaymentRepository_CreateDistributionTX_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentRepository_CreateDistributionTX_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, *domain.PaymentDistribution) error) *MockPaymentRepository_CreateDistributionTX_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTX provides a mock function with given fields: ctx, tx, p
func (_m *MockPaymentRepository) CreateTX(ctx context.Context, tx *sqlx.Tx, p *domain.Payment) error {
	ret := _m.Called(ctx, tx, p)

	if len(ret) == 0 {
		panic("no return value specified for CreateTX")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *domain.Payment) error); ok {
		r0 = rf(ctx, tx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentRepository_CreateTX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTX'
type MockPaymentRepository_CreateTX_Call struct {
	*mock.Call
}

// CreateTX is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - p *domain.Payment
func (_e *MockPaymentRepository_Expecter) CreateTX(ctx interface{}, tx interface{}, p interface{}) *MockPaymentRepository_CreateTX_Call {
	return &MockPaymentRepository_CreateTX_Call{Call: _e.mock.On("CreateTX", ctx, tx, p)}
}

func (_c *MockPaymentRepository_CreateTX_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, p *domain.Payment)) *MockPaymentRepository_CreateTX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(*domain.Payment))
	})
	return _c
}

func (_c *MockPaymentRepository_CreateTX_Call) Return(_a0 error) *MockPaymentRepository_CreateTX_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentRepository_CreateTX_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, *domain.Payment) error) *MockPaymentRepository_CreateTX_Call {
	_c.Call.Return(run)
	return _c
}

// GetByExternalID provides a mock function with given fields: ctx, externalID
func (_m *MockPaymentRepository) GetByExternalID(ctx context.Context, externalID string) (*domain.Payment, error) {
	ret := _m.Called(ctx, externalID)

	if len(ret) == 0 {
		panic("no return value specified for GetByExternalID")
	}

	var r0 *domain.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Payment, error)); ok {
		return rf(ctx, externalID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Payment); ok {
		r0 = rf(ctx, externalID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, externalID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepository_GetByExternalID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByExternalID'
type MockPaymentRepository_GetByExternalID_Call struct {
	*mock.Call
}

// GetByExternalID is a helper method to define mock.On call
//   - ctx context.Context
//   - externalID string
func (_e *MockPaymentRepository_Expecter) GetByExternalID(ctx interface{}, externalID interface{}) *MockPaymentRepository_GetByExternalID_Call {
	return &MockPaymentRepository_GetByExternalID_Call{Call: _e.mock.On("GetByExternalID", ctx, externalID)}
}

func (_c *MockPaymentRepository_GetByExternalID_Call) Run(run func(ctx context.Context, externalID string)) *MockPaymentRepository_GetByExternalID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPaymentRepository_GetByExternalID_Call) Return(_a0 *domain.Payment, _a1 error) *MockPaymentRepository_GetByExternalID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepository_GetByExternalID_Call) RunAndReturn(run func(context.Context, string) (*domain.Payment, error)) *MockPaymentRepository_GetByExternalID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByExternalIDForUpdateTX provides a mock function with given fields: ctx, tx, externalID
func (_m *MockPaymentRepository) GetByExternalIDForUpdateTX(ctx context.Context, tx *sqlx.Tx, externalID string) (*domain.Payment, error) {
	ret := _m.Called(ctx, tx, externalID)

	if len(ret) == 0 {
		panic("no return value specified for GetByExternalIDForUpdateTX")
	}

	var r0 *domain.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string) (*domain.Payment, error)); ok {
		return rf(ctx, tx, externalID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, string) *domain.Payment); ok {
		r0 = rf(ctx, tx, externalID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, string) error); ok {
		r1 = rf(ctx, tx, externalID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepository_GetByExternalIDForUpdateTX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByExternalIDForUpdateTX'
type MockPaymentRepository_GetByExternalIDForUpdateTX_Call struct {
	*mock.Call
}

// GetByExternalIDForUpdateTX is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - externalID string
func (_e *MockPaymentRepository_Expecter) GetByExternalIDForUpdateTX(ctx interface{}, tx interface{}, externalID interface{}) *MockPaymentRepository_GetByExternalIDForUpdateTX_Call {
	return &MockPaymentRepository_GetByExternalIDForUpdateTX_Call{Call: _e.mock.On("GetByExternalIDForUpdateTX", ctx, tx, externalID)}
}

func (_c *MockPaymentRepository_GetByExternalIDForUpdateTX_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, externalID string)) *MockPaymentRepository_GetByExternalIDForUpdateTX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(string))
	})
	return _c
}

func (_c *MockPaymentRepository_GetByExternalIDForUpdateTX_Call) Return(_a0 *domain.Payment, _a1 error) *MockPaymentRepository_GetByExternalIDForUpdateTX_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepository_GetByExternalIDForUpdateTX_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, string) (*domain.Payment, error)) *MockPaymentRepository_GetByExternalIDForUpdateTX_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockPaymentRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Payment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Payment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Payment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockPaymentRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockPaymentRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockPaymentRepository_GetByID_Call {
	return &MockPaymentRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockPaymentRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockPaymentRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockPaymentRepository_GetByID_Call) Return(_a0 *domain.Payment, _a1 error) *MockPaymentRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Payment, error)) *MockPaymentRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDForUpdateTX provides a mock function with given fields: ctx, tx, id
func (_m *MockPaymentRepository) GetByIDForUpdateTX(ctx context.Context, tx *sqlx.Tx, id uuid.UUID) (*domain.Payment, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDForUpdateTX")
	}

	var r0 *domain.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) (*domain.Payment, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) *domain.Payment); ok {
		r0 = rf(ctx, tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepository_GetByIDForUpdateTX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDForUpdateTX'
type MockPaymentRepository_GetByIDForUpdateTX_Call struct {
	*mock.Call
}

// GetByIDForUpdateTX is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - id uuid.UUID
func (_e *MockPaymentRepository_Expecter) GetByIDForUpdateTX(ctx interface{}, tx interface{}, id interface{}) *MockPaymentRepository_GetByIDForUpdateTX_Call {
	return &MockPaymentRepository_GetByIDForUpdateTX_Call{Call: _e.mock.On("GetByIDForUpdateTX", ctx, tx, id)}
}

func (_c *MockPaymentRepository_GetByIDForUpdateTX_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, id uuid.UUID)) *MockPaymentRepository_GetByIDForUpdateTX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockPaymentRepository_GetByIDForUpdateTX_Call) Return(_a0 *domain.Payment, _a1 error) *MockPaymentRepository_GetByIDForUpdateTX_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepository_GetByIDForUpdateTX_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID) (*domain.Payment, error)) *MockPaymentRepository_GetByIDForUpdateTX_Call {
	_c.Call.Return(run)
	return _c
}

// GetDistributionsByPaymentID provides a mock function with given fields: ctx, paymentID
func (_m *MockPaymentRepository) GetDistributionsByPaymentID(ctx context.Context, paymentID uuid.UUID) ([]domain.PaymentDistribution, error) {
	ret := _m.Called(ctx, paymentID)

	if len(ret) == 0 {
		panic("no return value specified for GetDistributionsByPaymentID")
	}

	var r0 []domain.PaymentDistribution
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.PaymentDistribution, error)); ok {
		return rf(ctx, paymentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.PaymentDistribution); ok {
		r0 = rf(ctx, paymentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PaymentDistribution)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, paymentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepository_GetDistributionsByPaymentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDistributionsByPaymentID'
type MockPaymentRepository_GetDistributionsByPaymentID_Call struct {
	*mock.Call
}

// GetDistributionsByPaymentID is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentID uuid.UUID
func (_e *MockPaymentRepository_Expecter) GetDistributionsByPaymentID(ctx interface{}, paymentID interface{}) *MockPaymentRepository_GetDistributionsByPaymentID_Call {
	return &MockPaymentRepository_GetDistributionsByPaymentID_Call{Call: _e.mock.On("GetDistributionsByPaymentID", ctx, paymentID)}
}

func (_c *MockPaymentRepository_GetDistributionsByPaymentID_Call) Run(run func(ctx context.Context, paymentID uuid.UUID)) *MockPaymentRepository_GetDistributionsByPaymentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockPaymentRepository_GetDistributionsByPaymentID_Call) Return(_a0 []domain.PaymentDistribution, _a1 error) *MockPaymentRepository_GetDistributionsByPaymentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepository_GetDistributionsByPaymentID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]domain.PaymentDistribution, error)) *MockPaymentRepository_GetDistributionsByPaymentID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSnapTokenTX provides a mock function with given fields: ctx, tx, id, snapToken
func (_m *MockPaymentRepository) UpdateSnapTokenTX(ctx context.Context, tx *sqlx.Tx, id uuid.UUID, snapToken string) error {
	ret := _m.Called(ctx, tx, id, snapToken)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSnapTokenTX")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, string) error); ok {
		r0 = rf(ctx, tx, id, snapToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentRepository_UpdateSnapTokenTX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSnapTokenTX'
type MockPaymentRepository_UpdateSnapTokenTX_Call struct {
	*mock.Call
}

// UpdateSnapTokenTX is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - id uuid.UUID
//   - snapToken string
func (_e *MockPaymentRepository_Expecter) UpdateSnapTokenTX(ctx interface{}, tx interface{}, id interface{}, snapToken interface{}) *MockPaymentRepository_UpdateSnapTokenTX_Call {
	return &MockPaymentRepository_UpdateSnapTokenTX_Call{Call: _e.mock.On("UpdateSnapTokenTX", ctx, tx, id, snapToken)}
}

func (_c *MockPaymentRepository_UpdateSnapTokenTX_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, id uuid.UUID, snapToken string)) *MockPaymentRepository_UpdateSnapTokenTX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *MockPaymentRepository_UpdateSnapTokenTX_Call) Return(_a0 error) *MockPaymentRepository_UpdateSnapTokenTX_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentRepository_UpdateSnapTokenTX_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID, string) error) *MockPaymentRepository_UpdateSnapTokenTX_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatusTX provides a mock function with given fields: ctx, tx, id, status, externalID
func (_m *MockPaymentRepository) UpdateStatusTX(ctx context.Context, tx *sqlx.Tx, id uuid.UUID, status domain.PaymentStatus, externalID *string) error {
	ret := _m.Called(ctx, tx, id, status, externalID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusTX")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, domain.PaymentStatus, *string) error); ok {
		r0 = rf(ctx, tx, id, status, externalID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentRepository_UpdateStatusTX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatusTX'
type MockPaymentRepository_UpdateStatusTX_Call struct {
	*mock.Call
}

// UpdateStatusTX is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - id uuid.UUID
//   - status domain.PaymentStatus
//   - externalID *string
func (_e *MockPaymentRepository_Expecter) UpdateStatusTX(ctx interface{}, tx interface{}, id interface{}, status interface{}, externalID interface{}) *MockPaymentRepository_UpdateStatusTX_Call {
	return &MockPaymentRepository_UpdateStatusTX_Call{Call: _e.mock.On("UpdateStatusTX", ctx, tx, id, status, externalID)}
}

func (_c *MockPaymentRepository_UpdateStatusTX_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, id uuid.UUID, status domain.PaymentStatus, externalID *string)) *MockPaymentRepository_UpdateStatusTX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID), args[3].(domain.PaymentStatus), args[4].(*string))
	})
	return _c
}

func (_c *MockPaymentRepository_UpdateStatusTX_Call) Return(_a0 error) *MockPaymentRepository_UpdateStatusTX_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentRepository_UpdateStatusTX_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID, domain.PaymentStatus, *string) error) *MockPaymentRepository_UpdateStatusTX_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentRepository creates a new instance of MockPaymentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentRepository {
	mock := &MockPaymentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
