// Code generated by mockery v2.53.6. DO NOT EDIT.

package payment

import (
	context "context"
	domain "go-marketplace/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockPaymentProvider is an autogenerated mock type for the PaymentProvider type
type MockPaymentProvider struct {
	mock.Mock
}

type MockPaymentProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentProvider) EXPECT() *MockPaymentProvider_Expecter {
	return &MockPaymentProvider_Expecter{mock: &_m.Mock}
}

// CreateTransaction provides a mock function with given fields: ctx, p
func (_m *MockPaymentProvider) CreateTransaction(ctx context.Context, p *domain.Payment) (string, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Payment) (string, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Payment) string); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Payment) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentProvider_CreateTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTransaction'
type MockPaymentProvider_CreateTransaction_Call struct {
	*mock.Call
}

// CreateTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - p *domain.Payment
func (_e *MockPaymentProvider_Expecter) CreateTransaction(ctx interface{}, p interface{}) *MockPaymentProvider_CreateTransaction_Call {
	return &MockPaymentProvider_CreateTransaction_Call{Call: _e.mock.On("CreateTransaction", ctx, p)}
}

func (_c *MockPaymentProvider_CreateTransaction_Call) Run(run func(ctx context.Context, p *domain.Payment)) *MockPaymentProvider_CreateTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Payment))
	})
	return _c
}

func (_c *MockPaymentProvider_CreateTransaction_Call) Return(_a0 string, _a1 error) *MockPaymentProvider_CreateTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentProvider_CreateTransaction_Call) RunAndReturn(run func(context.Context, *domain.Payment) (string, error)) *MockPaymentProvider_CreateTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentProvider creates a new instance of MockPaymentProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentProvider {
	mock := &MockPaymentProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
