// Code generated by mockery v2.53.6. DO NOT EDIT.

package payment

import (
	context "context"
	domain "go-marketplace/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockOrderManager is an autogenerated mock type for the OrderManager type
type MockOrderManager struct {
	mock.Mock
}

type MockOrderManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderManager) EXPECT() *MockOrderManager_Expecter {
	return &MockOrderManager_Expecter{mock: &_m.Mock}
}

// HandlePaymentStatusChange provides a mock function with given fields: ctx, paymentID, status
func (_m *MockOrderManager) HandlePaymentStatusChange(ctx context.Context, paymentID uuid.UUID, status domain.PaymentStatus) error {
	ret := _m.Called(ctx, paymentID, status)

	if len(ret) == 0 {
		panic("no return value specified for HandlePaymentStatusChange")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.PaymentStatus) error); ok {
		r0 = rf(ctx, paymentID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderManager_HandlePaymentStatusChange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandlePaymentStatusChange'
type MockOrderManager_HandlePaymentStatusChange_Call struct {
	*mock.Call
}

// HandlePaymentStatusChange is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentID uuid.UUID
//   - status domain.PaymentStatus
func (_e *MockOrderManager_Expecter) HandlePaymentStatusChange(ctx interface{}, paymentID interface{}, status interface{}) *MockOrderManager_HandlePaymentStatusChange_Call {
	return &MockOrderManager_HandlePaymentStatusChange_Call{Call: _e.mock.On("HandlePaymentStatusChange", ctx, paymentID, status)}
}

func (_c *MockOrderManager_HandlePaymentStatusChange_Call) Run(run func(ctx context.Context, paymentID uuid.UUID, status domain.PaymentStatus)) *MockOrderManager_HandlePaymentStatusChange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(domain.PaymentStatus))
	})
	return _c
}

func (_c *MockOrderManager_HandlePaymentStatusChange_Call) Return(_a0 error) *MockOrderManager_HandlePaymentStatusChange_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderManager_HandlePaymentStatusChange_Call) RunAndReturn(run func(context.Context, uuid.UUID, domain.PaymentStatus) error) *MockOrderManager_HandlePaymentStatusChange_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderManager creates a new instance of MockOrderManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderManager {
	mock := &MockOrderManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
