// Code generated by mockery v2.53.6. DO NOT EDIT.

package payment

import (
	context "context"
	domain "go-marketplace/internal/domain"

	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"
)

// MockPaymentServiceInterface is an autogenerated mock type for the PaymentServiceInterface type
type MockPaymentServiceInterface struct {
	mock.Mock
}

type MockPaymentServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentServiceInterface) EXPECT() *MockPaymentServiceInterface_Expecter {
	return &MockPaymentServiceInterface_Expecter{mock: &_m.Mock}
}

// CreatePaymentTX provides a mock function with given fields: ctx, tx, req
func (_m *MockPaymentServiceInterface) CreatePaymentTX(ctx context.Context, tx *sqlx.Tx, req CreatePaymentRequest) (*PaymentResponse, error) {
	ret := _m.Called(ctx, tx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreatePaymentTX")
	}

	var r0 *PaymentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, CreatePaymentRequest) (*PaymentResponse, error)); ok {
		return rf(ctx, tx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, CreatePaymentRequest) *PaymentResponse); ok {
		r0 = rf(ctx, tx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*PaymentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, CreatePaymentRequest) error); ok {
		r1 = rf(ctx, tx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentServiceInterface_CreatePaymentTX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePaymentTX'
type MockPaymentServiceInterface_CreatePaymentTX_Call struct {
	*mock.Call
}

// CreatePaymentTX is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - req CreatePaymentRequest
func (_e *MockPaymentServiceInterface_Expecter) CreatePaymentTX(ctx interface{}, tx interface{}, req interface{}) *MockPaymentServiceInterface_CreatePaymentTX_Call {
	return &MockPaymentServiceInterface_CreatePaymentTX_Call{Call: _e.mock.On("CreatePaymentTX", ctx, tx, req)}
}

func (_c *MockPaymentServiceInterface_CreatePaymentTX_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, req CreatePaymentRequest)) *MockPaymentServiceInterface_CreatePaymentTX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(CreatePaymentRequest))
	})
	return _c
}

func (_c *MockPaymentServiceInterface_CreatePaymentTX_Call) Return(_a0 *PaymentResponse, _a1 error) *MockPaymentServiceInterface_CreatePaymentTX_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentServiceInterface_CreatePaymentTX_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, CreatePaymentRequest) (*PaymentResponse, error)) *MockPaymentServiceInterface_CreatePaymentTX_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessWebhook provides a mock function with given fields: ctx, externalID, status
func (_m *MockPaymentServiceInterface) ProcessWebhook(ctx context.Context, externalID string, status domain.PaymentStatus) error {
	ret := _m.Called(ctx, externalID, status)

	if len(ret) == 0 {
		panic("no return value specified for ProcessWebhook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.PaymentStatus) error); ok {
		r0 = rf(ctx, externalID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentServiceInterface_ProcessWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessWebhook'
type MockPaymentServiceInterface_ProcessWebhook_Call struct {
	*mock.Call
}

// ProcessWebhook is a helper method to define mock.On call
//   - ctx context.Context
//   - externalID string
//   - status domain.PaymentStatus
func (_e *MockPaymentServiceInterface_Expecter) ProcessWebhook(ctx interface{}, externalID interface{}, status interface{}) *MockPaymentServiceInterface_ProcessWebhook_Call {
	return &MockPaymentServiceInterface_ProcessWebhook_Call{Call: _e.mock.On("ProcessWebhook", ctx, externalID, status)}
}

func (_c *MockPaymentServiceInterface_ProcessWebhook_Call) Run(run func(ctx context.Context, externalID string, status domain.PaymentStatus)) *MockPaymentServiceInterface_ProcessWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.PaymentStatus))
	})
	return _c
}

func (_c *MockPaymentServiceInterface_ProcessWebhook_Call) Return(_a0 error) *MockPaymentServiceInterface_ProcessWebhook_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentServiceInterface_ProcessWebhook_Call) RunAndReturn(run func(context.Context, string, domain.PaymentStatus) error) *MockPaymentServiceInterface_ProcessWebhook_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentServiceInterface creates a new instance of MockPaymentServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentServiceInterface {
	mock := &MockPaymentServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
