// Code generated by mockery v2.53.6. DO NOT EDIT.

package order

import (
	context "context"
	domain "go-marketplace/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockOrderService is an autogenerated mock type for the OrderService type
type MockOrderService struct {
	mock.Mock
}

type MockOrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderService) EXPECT() *MockOrderService_Expecter {
	return &MockOrderService_Expecter{mock: &_m.Mock}
}

// AppealUserOrder provides a mock function with given fields: ctx, userID, orderID, reason
func (_m *MockOrderService) AppealUserOrder(ctx context.Context, userID uuid.UUID, orderID uuid.UUID, reason string) error {
	ret := _m.Called(ctx, userID, orderID, reason)

	if len(ret) == 0 {
		panic("no return value specified for AppealUserOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, userID, orderID, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderService_AppealUserOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppealUserOrder'
type MockOrderService_AppealUserOrder_Call struct {
	*mock.Call
}

// AppealUserOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - orderID uuid.UUID
//   - reason string
func (_e *MockOrderService_Expecter) AppealUserOrder(ctx interface{}, userID interface{}, orderID interface{}, reason interface{}) *MockOrderService_AppealUserOrder_Call {
	return &MockOrderService_AppealUserOrder_Call{Call: _e.mock.On("AppealUserOrder", ctx, userID, orderID, reason)}
}

func (_c *MockOrderService_AppealUserOrder_Call) Run(run func(ctx context.Context, userID uuid.UUID, orderID uuid.UUID, reason string)) *MockOrderService_AppealUserOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *MockOrderService_AppealUserOrder_Call) Return(_a0 error) *MockOrderService_AppealUserOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderService_AppealUserOrder_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) error) *MockOrderService_AppealUserOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CancelUserOrder provides a mock function with given fields: ctx, userID, orderID
func (_m *MockOrderService) CancelUserOrder(ctx context.Context, userID uuid.UUID, orderID uuid.UUID) error {
	ret := _m.Called(ctx, userID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for CancelUserOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, orderID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderService_CancelUserOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelUserOrder'
type MockOrderService_CancelUserOrder_Call struct {
	*mock.Call
}

// CancelUserOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - orderID uuid.UUID
func (_e *MockOrderService_Expecter) CancelUserOrder(ctx interface{}, userID interface{}, orderID interface{}) *MockOrderService_CancelUserOrder_Call {
	return &MockOrderService_CancelUserOrder_Call{Call: _e.mock.On("CancelUserOrder", ctx, userID, orderID)}
}

func (_c *MockOrderService_CancelUserOrder_Call) Run(run func(ctx context.Context, userID uuid.UUID, orderID uuid.UUID)) *MockOrderService_CancelUserOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrderService_CancelUserOrder_Call) Return(_a0 error) *MockOrderService_CancelUserOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderService_CancelUserOrder_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockOrderService_CancelUserOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUserCheckout provides a mock function with given fields: ctx, userID, req
func (_m *MockOrderService) CreateUserCheckout(ctx context.Context, userID uuid.UUID, req CheckoutRequest) (*OrderPaymentResponse, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserCheckout")
	}

	var r0 *OrderPaymentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, CheckoutRequest) (*OrderPaymentResponse, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, CheckoutRequest) *OrderPaymentResponse); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*OrderPaymentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, CheckoutRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderService_CreateUserCheckout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserCheckout'
type MockOrderService_CreateUserCheckout_Call struct {
	*mock.Call
}

// CreateUserCheckout is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req CheckoutRequest
func (_e *MockOrderService_Expecter) CreateUserCheckout(ctx interface{}, userID interface{}, req interface{}) *MockOrderService_CreateUserCheckout_Call {
	return &MockOrderService_CreateUserCheckout_Call{Call: _e.mock.On("CreateUserCheckout", ctx, userID, req)}
}

func (_c *MockOrderService_CreateUserCheckout_Call) Run(run func(ctx context.Context, userID uuid.UUID, req CheckoutRequest)) *MockOrderService_CreateUserCheckout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(CheckoutRequest))
	})
	return _c
}

func (_c *MockOrderService_CreateUserCheckout_Call) Return(_a0 *OrderPaymentResponse, _a1 error) *MockOrderService_CreateUserCheckout_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderService_CreateUserCheckout_Call) RunAndReturn(run func(context.Context, uuid.UUID, CheckoutRequest) (*OrderPaymentResponse, error)) *MockOrderService_CreateUserCheckout_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: ctx, id
func (_m *MockOrderService) GetOrder(ctx context.Context, id uuid.UUID) (*OrderResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *OrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*OrderResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *OrderResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*OrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderService_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockOrderService_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockOrderService_Expecter) GetOrder(ctx interface{}, id interface{}) *MockOrderService_GetOrder_Call {
	return &MockOrderService_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, id)}
}

func (_c *MockOrderService_GetOrder_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockOrderService_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrderService_GetOrder_Call) Return(_a0 *OrderResponse, _a1 error) *MockOrderService_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderService_GetOrder_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*OrderResponse, error)) *MockOrderService_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// MerchantCancelOrder provides a mock function with given fields: ctx, merchantID, orderID
func (_m *MockOrderService) MerchantCancelOrder(ctx context.Context, merchantID uuid.UUID, orderID uuid.UUID) error {
	ret := _m.Called(ctx, merchantID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for MerchantCancelOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, merchantID, orderID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderService_MerchantCancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MerchantCancelOrder'
type MockOrderService_MerchantCancelOrder_Call struct {
	*mock.Call
}

// MerchantCancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - orderID uuid.UUID
func (_e *MockOrderService_Expecter) MerchantCancelOrder(ctx interface{}, merchantID interface{}, orderID interface{}) *MockOrderService_MerchantCancelOrder_Call {
	return &MockOrderService_MerchantCancelOrder_Call{Call: _e.mock.On("MerchantCancelOrder", ctx, merchantID, orderID)}
}

func (_c *MockOrderService_MerchantCancelOrder_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, orderID uuid.UUID)) *MockOrderService_MerchantCancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrderService_MerchantCancelOrder_Call) Return(_a0 error) *MockOrderService_MerchantCancelOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderService_MerchantCancelOrder_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockOrderService_MerchantCancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// MerchantUpdateStatus provides a mock function with given fields: ctx, merchantID, orderID, status
func (_m *MockOrderService) MerchantUpdateStatus(ctx context.Context, merchantID uuid.UUID, orderID uuid.UUID, status domain.OrderStatus) error {
	ret := _m.Called(ctx, merchantID, orderID, status)

	if len(ret) == 0 {
		panic("no return value specified for MerchantUpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, domain.OrderStatus) error); ok {
		r0 = rf(ctx, merchantID, orderID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderService_MerchantUpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MerchantUpdateStatus'
type MockOrderService_MerchantUpdateStatus_Call struct {
	*mock.Call
}

// MerchantUpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - orderID uuid.UUID
//   - status domain.OrderStatus
func (_e *MockOrderService_Expecter) MerchantUpdateStatus(ctx interface{}, merchantID interface{}, orderID interface{}, status interface{}) *MockOrderService_MerchantUpdateStatus_Call {
	return &MockOrderService_MerchantUpdateStatus_Call{Call: _e.mock.On("MerchantUpdateStatus", ctx, merchantID, orderID, status)}
}

func (_c *MockOrderService_MerchantUpdateStatus_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, orderID uuid.UUID, status domain.OrderStatus)) *MockOrderService_MerchantUpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(domain.OrderStatus))
	})
	return _c
}

func (_c *MockOrderService_MerchantUpdateStatus_Call) Return(_a0 error) *MockOrderService_MerchantUpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderService_MerchantUpdateStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, domain.OrderStatus) error) *MockOrderService_MerchantUpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderService creates a new instance of MockOrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderService {
	mock := &MockOrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
