// Code generated by mockery v2.53.6. DO NOT EDIT.

package product

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockProductService is an autogenerated mock type for the ProductService type
type MockProductService struct {
	mock.Mock
}

type MockProductService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductService) EXPECT() *MockProductService_Expecter {
	return &MockProductService_Expecter{mock: &_m.Mock}
}

// CreateProduct provides a mock function with given fields: ctx, userID, req
func (_m *MockProductService) CreateProduct(ctx context.Context, userID uuid.UUID, req ProductCreateRequest) (*ProductResponse, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 *ProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, ProductCreateRequest) (*ProductResponse, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, ProductCreateRequest) *ProductResponse); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, ProductCreateRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductService_CreateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProduct'
type MockProductService_CreateProduct_Call struct {
	*mock.Call
}

// CreateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req ProductCreateRequest
func (_e *MockProductService_Expecter) CreateProduct(ctx interface{}, userID interface{}, req interface{}) *MockProductService_CreateProduct_Call {
	return &MockProductService_CreateProduct_Call{Call: _e.mock.On("CreateProduct", ctx, userID, req)}
}

func (_c *MockProductService_CreateProduct_Call) Run(run func(ctx context.Context, userID uuid.UUID, req ProductCreateRequest)) *MockProductService_CreateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(ProductCreateRequest))
	})
	return _c
}

func (_c *MockProductService_CreateProduct_Call) Return(_a0 *ProductResponse, _a1 error) *MockProductService_CreateProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductService_CreateProduct_Call) RunAndReturn(run func(context.Context, uuid.UUID, ProductCreateRequest) (*ProductResponse, error)) *MockProductService_CreateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// SearchProducts provides a mock function with given fields: ctx, req
func (_m *MockProductService) SearchProducts(ctx context.Context, req ProductSearchRequest) ([]ProductResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SearchProducts")
	}

	var r0 []ProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ProductSearchRequest) ([]ProductResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ProductSearchRequest) []ProductResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ProductSearchRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductService_SearchProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchProducts'
type MockProductService_SearchProducts_Call struct {
	*mock.Call
}

// SearchProducts is a helper method to define mock.On call
//   - ctx context.Context
//   - req ProductSearchRequest
func (_e *MockProductService_Expecter) SearchProducts(ctx interface{}, req interface{}) *MockProductService_SearchProducts_Call {
	return &MockProductService_SearchProducts_Call{Call: _e.mock.On("SearchProducts", ctx, req)}
}

func (_c *MockProductService_SearchProducts_Call) Run(run func(ctx context.Context, req ProductSearchRequest)) *MockProductService_SearchProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ProductSearchRequest))
	})
	return _c
}

func (_c *MockProductService_SearchProducts_Call) Return(_a0 []ProductResponse, _a1 error) *MockProductService_SearchProducts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductService_SearchProducts_Call) RunAndReturn(run func(context.Context, ProductSearchRequest) ([]ProductResponse, error)) *MockProductService_SearchProducts_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProduct provides a mock function with given fields: ctx, userID, id, req
func (_m *MockProductService) UpdateProduct(ctx context.Context, userID uuid.UUID, id uuid.UUID, req ProductUpdateRequest) (*ProductResponse, error) {
	ret := _m.Called(ctx, userID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProduct")
	}

	var r0 *ProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, ProductUpdateRequest) (*ProductResponse, error)); ok {
		return rf(ctx, userID, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, ProductUpdateRequest) *ProductResponse); ok {
		r0 = rf(ctx, userID, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, ProductUpdateRequest) error); ok {
		r1 = rf(ctx, userID, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductService_UpdateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProduct'
type MockProductService_UpdateProduct_Call struct {
	*mock.Call
}

// UpdateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - id uuid.UUID
//   - req ProductUpdateRequest
func (_e *MockProductService_Expecter) UpdateProduct(ctx interface{}, userID interface{}, id interface{}, req interface{}) *MockProductService_UpdateProduct_Call {
	return &MockProductService_UpdateProduct_Call{Call: _e.mock.On("UpdateProduct", ctx, userID, id, req)}
}

func (_c *MockProductService_UpdateProduct_Call) Run(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID, req ProductUpdateRequest)) *MockProductService_UpdateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(ProductUpdateRequest))
	})
	return _c
}

func (_c *MockProductService_UpdateProduct_Call) Return(_a0 *ProductResponse, _a1 error) *MockProductService_UpdateProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductService_UpdateProduct_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, ProductUpdateRequest) (*ProductResponse, error)) *MockProductService_UpdateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductService creates a new instance of MockProductService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductService {
	mock := &MockProductService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
