// Code generated by mockery v2.53.6. DO NOT EDIT.

package product

import (
	context "context"
	domain "go-marketplace/internal/domain"

	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"

	uuid "github.com/google/uuid"
)

// MockProductRepository is an autogenerated mock type for the ProductRepository type
type MockProductRepository struct {
	mock.Mock
}

type MockProductRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductRepository) EXPECT() *MockProductRepository_Expecter {
	return &MockProductRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, p
func (_m *MockProductRepository) Create(ctx context.Context, p *domain.Product) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Product) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProductRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - p *domain.Product
func (_e *MockProductRepository_Expecter) Create(ctx interface{}, p interface{}) *MockProductRepository_Create_Call {
	return &MockProductRepository_Create_Call{Call: _e.mock.On("Create", ctx, p)}
}

func (_c *MockProductRepository_Create_Call) Run(run func(ctx context.Context, p *domain.Product)) *MockProductRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Product))
	})
	return _c
}

func (_c *MockProductRepository_Create_Call) Return(_a0 error) *MockProductRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Product) error) *MockProductRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockProductRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Product, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Product, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Product); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockProductRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockProductRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockProductRepository_GetByID_Call {
	return &MockProductRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockProductRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockProductRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProductRepository_GetByID_Call) Return(_a0 *domain.Product, _a1 error) *MockProductRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Product, error)) *MockProductRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDForUpdateTX provides a mock function with given fields: ctx, tx, id
func (_m *MockProductRepository) GetByIDForUpdateTX(ctx context.Context, tx *sqlx.Tx, id uuid.UUID) (*domain.Product, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDForUpdateTX")
	}

	var r0 *domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) (*domain.Product, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID) *domain.Product); ok {
		r0 = rf(ctx, tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uuid.UUID) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_GetByIDForUpdateTX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDForUpdateTX'
type MockProductRepository_GetByIDForUpdateTX_Call struct {
	*mock.Call
}

// GetByIDForUpdateTX is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - id uuid.UUID
func (_e *MockProductRepository_Expecter) GetByIDForUpdateTX(ctx interface{}, tx interface{}, id interface{}) *MockProductRepository_GetByIDForUpdateTX_Call {
	return &MockProductRepository_GetByIDForUpdateTX_Call{Call: _e.mock.On("GetByIDForUpdateTX", ctx, tx, id)}
}

func (_c *MockProductRepository_GetByIDForUpdateTX_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, id uuid.UUID)) *MockProductRepository_GetByIDForUpdateTX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockProductRepository_GetByIDForUpdateTX_Call) Return(_a0 *domain.Product, _a1 error) *MockProductRepository_GetByIDForUpdateTX_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_GetByIDForUpdateTX_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID) (*domain.Product, error)) *MockProductRepository_GetByIDForUpdateTX_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreStockBatchTX provides a mock function with given fields: ctx, tx, items
func (_m *MockProductRepository) RestoreStockBatchTX(ctx context.Context, tx *sqlx.Tx, items []domain.OrderItem) error {
	ret := _m.Called(ctx, tx, items)

	if len(ret) == 0 {
		panic("no return value specified for RestoreStockBatchTX")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, []domain.OrderItem) error); ok {
		r0 = rf(ctx, tx, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepository_RestoreStockBatchTX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreStockBatchTX'
type MockProductRepository_RestoreStockBatchTX_Call struct {
	*mock.Call
}

// RestoreStockBatchTX is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - items []domain.OrderItem
func (_e *MockProductRepository_Expecter) RestoreStockBatchTX(ctx interface{}, tx interface{}, items interface{}) *MockProductRepository_RestoreStockBatchTX_Call {
	return &MockProductRepository_RestoreStockBatchTX_Call{Call: _e.mock.On("RestoreStockBatchTX", ctx, tx, items)}
}

func (_c *MockProductRepository_RestoreStockBatchTX_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, items []domain.OrderItem)) *MockProductRepository_RestoreStockBatchTX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].([]domain.OrderItem))
	})
	return _c
}

func (_c *MockProductRepository_RestoreStockBatchTX_Call) Return(_a0 error) *MockProductRepository_RestoreStockBatchTX_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepository_RestoreStockBatchTX_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, []domain.OrderItem) error) *MockProductRepository_RestoreStockBatchTX_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, query, limit, offset
func (_m *MockProductRepository) Search(ctx context.Context, query string, limit int, offset int) ([]domain.Product, error) {
	ret := _m.Called(ctx, query, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]domain.Product, error)); ok {
		return rf(ctx, query, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []domain.Product); ok {
		r0 = rf(ctx, query, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, query, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockProductRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - limit int
//   - offset int
func (_e *MockProductRepository_Expecter) Search(ctx interface{}, query interface{}, limit interface{}, offset interface{}) *MockProductRepository_Search_Call {
	return &MockProductRepository_Search_Call{Call: _e.mock.On("Search", ctx, query, limit, offset)}
}

func (_c *MockProductRepository_Search_Call) Run(run func(ctx context.Context, query string, limit int, offset int)) *MockProductRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockProductRepository_Search_Call) Return(_a0 []domain.Product, _a1 error) *MockProductRepository_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_Search_Call) RunAndReturn(run func(context.Context, string, int, int) ([]domain.Product, error)) *MockProductRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, p
func (_m *MockProductRepository) Update(ctx context.Context, p *domain.Product) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Product) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProductRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - p *domain.Product
func (_e *MockProductRepository_Expecter) Update(ctx interface{}, p interface{}) *MockProductRepository_Update_Call {
	return &MockProductRepository_Update_Call{Call: _e.mock.On("Update", ctx, p)}
}

func (_c *MockProductRepository_Update_Call) Run(run func(ctx context.Context, p *domain.Product)) *MockProductRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Product))
	})
	return _c
}

func (_c *MockProductRepository_Update_Call) Return(_a0 error) *MockProductRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Product) error) *MockProductRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStockTX provides a mock function with given fields: ctx, tx, id, stock
func (_m *MockProductRepository) UpdateStockTX(ctx context.Context, tx *sqlx.Tx, id uuid.UUID, stock int) error {
	ret := _m.Called(ctx, tx, id, stock)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStockTX")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uuid.UUID, int) error); ok {
		r0 = rf(ctx, tx, id, stock)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepository_UpdateStockTX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStockTX'
type MockProductRepository_UpdateStockTX_Call struct {
	*mock.Call
}

// UpdateStockTX is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - id uuid.UUID
//   - stock int
func (_e *MockProductRepository_Expecter) UpdateStockTX(ctx interface{}, tx interface{}, id interface{}, stock interface{}) *MockProductRepository_UpdateStockTX_Call {
	return &MockProductRepository_UpdateStockTX_Call{Call: _e.mock.On("UpdateStockTX", ctx, tx, id, stock)}
}

func (_c *MockProductRepository_UpdateStockTX_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, id uuid.UUID, stock int)) *MockProductRepository_UpdateStockTX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(uuid.UUID), args[3].(int))
	})
	return _c
}

func (_c *MockProductRepository_UpdateStockTX_Call) Return(_a0 error) *MockProductRepository_UpdateStockTX_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepository_UpdateStockTX_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, uuid.UUID, int) error) *MockProductRepository_UpdateStockTX_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductRepository creates a new instance of MockProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductRepository {
	mock := &MockProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
