// Code generated by mockery v2.53.6. DO NOT EDIT.

package order

import (
	context "context"
	domain "go-shop-yourself/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockOrderServiceInterface is an autogenerated mock type for the OrderServiceInterface type
type MockOrderServiceInterface struct {
	mock.Mock
}

type MockOrderServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderServiceInterface) EXPECT() *MockOrderServiceInterface_Expecter {
	return &MockOrderServiceInterface_Expecter{mock: &_m.Mock}
}

// AppealUserOrder provides a mock function with given fields: ctx, userID, orderID, reason
func (_m *MockOrderServiceInterface) AppealUserOrder(ctx context.Context, userID uuid.UUID, orderID uuid.UUID, reason string) error {
	ret := _m.Called(ctx, userID, orderID, reason)

	if len(ret) == 0 {
		panic("no return value specified for AppealUserOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, userID, orderID, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderServiceInterface_AppealUserOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppealUserOrder'
type MockOrderServiceInterface_AppealUserOrder_Call struct {
	*mock.Call
}

// AppealUserOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - orderID uuid.UUID
//   - reason string
func (_e *MockOrderServiceInterface_Expecter) AppealUserOrder(ctx interface{}, userID interface{}, orderID interface{}, reason interface{}) *MockOrderServiceInterface_AppealUserOrder_Call {
	return &MockOrderServiceInterface_AppealUserOrder_Call{Call: _e.mock.On("AppealUserOrder", ctx, userID, orderID, reason)}
}

func (_c *MockOrderServiceInterface_AppealUserOrder_Call) Run(run func(ctx context.Context, userID uuid.UUID, orderID uuid.UUID, reason string)) *MockOrderServiceInterface_AppealUserOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *MockOrderServiceInterface_AppealUserOrder_Call) Return(_a0 error) *MockOrderServiceInterface_AppealUserOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderServiceInterface_AppealUserOrder_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) error) *MockOrderServiceInterface_AppealUserOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CancelUserOrder provides a mock function with given fields: ctx, userID, orderID
func (_m *MockOrderServiceInterface) CancelUserOrder(ctx context.Context, userID uuid.UUID, orderID uuid.UUID) error {
	ret := _m.Called(ctx, userID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for CancelUserOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, orderID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderServiceInterface_CancelUserOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelUserOrder'
type MockOrderServiceInterface_CancelUserOrder_Call struct {
	*mock.Call
}

// CancelUserOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - orderID uuid.UUID
func (_e *MockOrderServiceInterface_Expecter) CancelUserOrder(ctx interface{}, userID interface{}, orderID interface{}) *MockOrderServiceInterface_CancelUserOrder_Call {
	return &MockOrderServiceInterface_CancelUserOrder_Call{Call: _e.mock.On("CancelUserOrder", ctx, userID, orderID)}
}

func (_c *MockOrderServiceInterface_CancelUserOrder_Call) Run(run func(ctx context.Context, userID uuid.UUID, orderID uuid.UUID)) *MockOrderServiceInterface_CancelUserOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrderServiceInterface_CancelUserOrder_Call) Return(_a0 error) *MockOrderServiceInterface_CancelUserOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderServiceInterface_CancelUserOrder_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockOrderServiceInterface_CancelUserOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUserCheckout provides a mock function with given fields: ctx, userID, req
func (_m *MockOrderServiceInterface) CreateUserCheckout(ctx context.Context, userID uuid.UUID, req CheckoutRequest) (*OrderPaymentResponse, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserCheckout")
	}

	var r0 *OrderPaymentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, CheckoutRequest) (*OrderPaymentResponse, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, CheckoutRequest) *OrderPaymentResponse); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*OrderPaymentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, CheckoutRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderServiceInterface_CreateUserCheckout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserCheckout'
type MockOrderServiceInterface_CreateUserCheckout_Call struct {
	*mock.Call
}

// CreateUserCheckout is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req CheckoutRequest
func (_e *MockOrderServiceInterface_Expecter) CreateUserCheckout(ctx interface{}, userID interface{}, req interface{}) *MockOrderServiceInterface_CreateUserCheckout_Call {
	return &MockOrderServiceInterface_CreateUserCheckout_Call{Call: _e.mock.On("CreateUserCheckout", ctx, userID, req)}
}

func (_c *MockOrderServiceInterface_CreateUserCheckout_Call) Run(run func(ctx context.Context, userID uuid.UUID, req CheckoutRequest)) *MockOrderServiceInterface_CreateUserCheckout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(CheckoutRequest))
	})
	return _c
}

func (_c *MockOrderServiceInterface_CreateUserCheckout_Call) Return(_a0 *OrderPaymentResponse, _a1 error) *MockOrderServiceInterface_CreateUserCheckout_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderServiceInterface_CreateUserCheckout_Call) RunAndReturn(run func(context.Context, uuid.UUID, CheckoutRequest) (*OrderPaymentResponse, error)) *MockOrderServiceInterface_CreateUserCheckout_Call {
	_c.Call.Return(run)
	return _c
}

// GetMerchantOrders provides a mock function with given fields: ctx, merchantID
func (_m *MockOrderServiceInterface) GetMerchantOrders(ctx context.Context, merchantID uuid.UUID) ([]OrderResponse, error) {
	ret := _m.Called(ctx, merchantID)

	if len(ret) == 0 {
		panic("no return value specified for GetMerchantOrders")
	}

	var r0 []OrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]OrderResponse, error)); ok {
		return rf(ctx, merchantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []OrderResponse); ok {
		r0 = rf(ctx, merchantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]OrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, merchantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderServiceInterface_GetMerchantOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMerchantOrders'
type MockOrderServiceInterface_GetMerchantOrders_Call struct {
	*mock.Call
}

// GetMerchantOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
func (_e *MockOrderServiceInterface_Expecter) GetMerchantOrders(ctx interface{}, merchantID interface{}) *MockOrderServiceInterface_GetMerchantOrders_Call {
	return &MockOrderServiceInterface_GetMerchantOrders_Call{Call: _e.mock.On("GetMerchantOrders", ctx, merchantID)}
}

func (_c *MockOrderServiceInterface_GetMerchantOrders_Call) Run(run func(ctx context.Context, merchantID uuid.UUID)) *MockOrderServiceInterface_GetMerchantOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrderServiceInterface_GetMerchantOrders_Call) Return(_a0 []OrderResponse, _a1 error) *MockOrderServiceInterface_GetMerchantOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderServiceInterface_GetMerchantOrders_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]OrderResponse, error)) *MockOrderServiceInterface_GetMerchantOrders_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: ctx, id
func (_m *MockOrderServiceInterface) GetOrder(ctx context.Context, id uuid.UUID) (*OrderResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *OrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*OrderResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *OrderResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*OrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderServiceInterface_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockOrderServiceInterface_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockOrderServiceInterface_Expecter) GetOrder(ctx interface{}, id interface{}) *MockOrderServiceInterface_GetOrder_Call {
	return &MockOrderServiceInterface_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, id)}
}

func (_c *MockOrderServiceInterface_GetOrder_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockOrderServiceInterface_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrderServiceInterface_GetOrder_Call) Return(_a0 *OrderResponse, _a1 error) *MockOrderServiceInterface_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderServiceInterface_GetOrder_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*OrderResponse, error)) *MockOrderServiceInterface_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserOrders provides a mock function with given fields: ctx, userID
func (_m *MockOrderServiceInterface) GetUserOrders(ctx context.Context, userID uuid.UUID) ([]OrderResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserOrders")
	}

	var r0 []OrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]OrderResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []OrderResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]OrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderServiceInterface_GetUserOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserOrders'
type MockOrderServiceInterface_GetUserOrders_Call struct {
	*mock.Call
}

// GetUserOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockOrderServiceInterface_Expecter) GetUserOrders(ctx interface{}, userID interface{}) *MockOrderServiceInterface_GetUserOrders_Call {
	return &MockOrderServiceInterface_GetUserOrders_Call{Call: _e.mock.On("GetUserOrders", ctx, userID)}
}

func (_c *MockOrderServiceInterface_GetUserOrders_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockOrderServiceInterface_GetUserOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrderServiceInterface_GetUserOrders_Call) Return(_a0 []OrderResponse, _a1 error) *MockOrderServiceInterface_GetUserOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderServiceInterface_GetUserOrders_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]OrderResponse, error)) *MockOrderServiceInterface_GetUserOrders_Call {
	_c.Call.Return(run)
	return _c
}

// MerchantCancelOrder provides a mock function with given fields: ctx, merchantID, orderID
func (_m *MockOrderServiceInterface) MerchantCancelOrder(ctx context.Context, merchantID uuid.UUID, orderID uuid.UUID) error {
	ret := _m.Called(ctx, merchantID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for MerchantCancelOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, merchantID, orderID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderServiceInterface_MerchantCancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MerchantCancelOrder'
type MockOrderServiceInterface_MerchantCancelOrder_Call struct {
	*mock.Call
}

// MerchantCancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - orderID uuid.UUID
func (_e *MockOrderServiceInterface_Expecter) MerchantCancelOrder(ctx interface{}, merchantID interface{}, orderID interface{}) *MockOrderServiceInterface_MerchantCancelOrder_Call {
	return &MockOrderServiceInterface_MerchantCancelOrder_Call{Call: _e.mock.On("MerchantCancelOrder", ctx, merchantID, orderID)}
}

func (_c *MockOrderServiceInterface_MerchantCancelOrder_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, orderID uuid.UUID)) *MockOrderServiceInterface_MerchantCancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrderServiceInterface_MerchantCancelOrder_Call) Return(_a0 error) *MockOrderServiceInterface_MerchantCancelOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderServiceInterface_MerchantCancelOrder_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockOrderServiceInterface_MerchantCancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// MerchantUpdateStatus provides a mock function with given fields: ctx, merchantID, orderID, status
func (_m *MockOrderServiceInterface) MerchantUpdateStatus(ctx context.Context, merchantID uuid.UUID, orderID uuid.UUID, status domain.OrderStatus) error {
	ret := _m.Called(ctx, merchantID, orderID, status)

	if len(ret) == 0 {
		panic("no return value specified for MerchantUpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, domain.OrderStatus) error); ok {
		r0 = rf(ctx, merchantID, orderID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderServiceInterface_MerchantUpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MerchantUpdateStatus'
type MockOrderServiceInterface_MerchantUpdateStatus_Call struct {
	*mock.Call
}

// MerchantUpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - orderID uuid.UUID
//   - status domain.OrderStatus
func (_e *MockOrderServiceInterface_Expecter) MerchantUpdateStatus(ctx interface{}, merchantID interface{}, orderID interface{}, status interface{}) *MockOrderServiceInterface_MerchantUpdateStatus_Call {
	return &MockOrderServiceInterface_MerchantUpdateStatus_Call{Call: _e.mock.On("MerchantUpdateStatus", ctx, merchantID, orderID, status)}
}

func (_c *MockOrderServiceInterface_MerchantUpdateStatus_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, orderID uuid.UUID, status domain.OrderStatus)) *MockOrderServiceInterface_MerchantUpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(domain.OrderStatus))
	})
	return _c
}

func (_c *MockOrderServiceInterface_MerchantUpdateStatus_Call) Return(_a0 error) *MockOrderServiceInterface_MerchantUpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderServiceInterface_MerchantUpdateStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, domain.OrderStatus) error) *MockOrderServiceInterface_MerchantUpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderServiceInterface creates a new instance of MockOrderServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderServiceInterface {
	mock := &MockOrderServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
