// Code generated by mockery v2.53.6. DO NOT EDIT.

package wallet

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockWalletServiceInterface is an autogenerated mock type for the WalletServiceInterface type
type MockWalletServiceInterface struct {
	mock.Mock
}

type MockWalletServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletServiceInterface) EXPECT() *MockWalletServiceInterface_Expecter {
	return &MockWalletServiceInterface_Expecter{mock: &_m.Mock}
}

// CreateWallet provides a mock function with given fields: ctx, userID
func (_m *MockWalletServiceInterface) CreateWallet(ctx context.Context, userID uuid.UUID) (*WalletResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateWallet")
	}

	var r0 *WalletResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*WalletResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *WalletResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*WalletResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletServiceInterface_CreateWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWallet'
type MockWalletServiceInterface_CreateWallet_Call struct {
	*mock.Call
}

// CreateWallet is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockWalletServiceInterface_Expecter) CreateWallet(ctx interface{}, userID interface{}) *MockWalletServiceInterface_CreateWallet_Call {
	return &MockWalletServiceInterface_CreateWallet_Call{Call: _e.mock.On("CreateWallet", ctx, userID)}
}

func (_c *MockWalletServiceInterface_CreateWallet_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockWalletServiceInterface_CreateWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockWalletServiceInterface_CreateWallet_Call) Return(_a0 *WalletResponse, _a1 error) *MockWalletServiceInterface_CreateWallet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletServiceInterface_CreateWallet_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*WalletResponse, error)) *MockWalletServiceInterface_CreateWallet_Call {
	_c.Call.Return(run)
	return _c
}

// GetWalletByUserID provides a mock function with given fields: ctx, userID
func (_m *MockWalletServiceInterface) GetWalletByUserID(ctx context.Context, userID uuid.UUID) (*WalletResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWalletByUserID")
	}

	var r0 *WalletResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*WalletResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *WalletResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*WalletResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletServiceInterface_GetWalletByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWalletByUserID'
type MockWalletServiceInterface_GetWalletByUserID_Call struct {
	*mock.Call
}

// GetWalletByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockWalletServiceInterface_Expecter) GetWalletByUserID(ctx interface{}, userID interface{}) *MockWalletServiceInterface_GetWalletByUserID_Call {
	return &MockWalletServiceInterface_GetWalletByUserID_Call{Call: _e.mock.On("GetWalletByUserID", ctx, userID)}
}

func (_c *MockWalletServiceInterface_GetWalletByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockWalletServiceInterface_GetWalletByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockWalletServiceInterface_GetWalletByUserID_Call) Return(_a0 *WalletResponse, _a1 error) *MockWalletServiceInterface_GetWalletByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletServiceInterface_GetWalletByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*WalletResponse, error)) *MockWalletServiceInterface_GetWalletByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetWalletHistory provides a mock function with given fields: ctx, userID, page, limit
func (_m *MockWalletServiceInterface) GetWalletHistory(ctx context.Context, userID uuid.UUID, page int, limit int) ([]TransactionResponse, error) {
	ret := _m.Called(ctx, userID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetWalletHistory")
	}

	var r0 []TransactionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]TransactionResponse, error)); ok {
		return rf(ctx, userID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []TransactionResponse); ok {
		r0 = rf(ctx, userID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]TransactionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, userID, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletServiceInterface_GetWalletHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWalletHistory'
type MockWalletServiceInterface_GetWalletHistory_Call struct {
	*mock.Call
}

// GetWalletHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - page int
//   - limit int
func (_e *MockWalletServiceInterface_Expecter) GetWalletHistory(ctx interface{}, userID interface{}, page interface{}, limit interface{}) *MockWalletServiceInterface_GetWalletHistory_Call {
	return &MockWalletServiceInterface_GetWalletHistory_Call{Call: _e.mock.On("GetWalletHistory", ctx, userID, page, limit)}
}

func (_c *MockWalletServiceInterface_GetWalletHistory_Call) Run(run func(ctx context.Context, userID uuid.UUID, page int, limit int)) *MockWalletServiceInterface_GetWalletHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockWalletServiceInterface_GetWalletHistory_Call) Return(_a0 []TransactionResponse, _a1 error) *MockWalletServiceInterface_GetWalletHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletServiceInterface_GetWalletHistory_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]TransactionResponse, error)) *MockWalletServiceInterface_GetWalletHistory_Call {
	_c.Call.Return(run)
	return _c
}

// Withdraw provides a mock function with given fields: ctx, userID, req
func (_m *MockWalletServiceInterface) Withdraw(ctx context.Context, userID uuid.UUID, req WithdrawRequest) error {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, WithdrawRequest) error); ok {
		r0 = rf(ctx, userID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWalletServiceInterface_Withdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdraw'
type MockWalletServiceInterface_Withdraw_Call struct {
	*mock.Call
}

// Withdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req WithdrawRequest
func (_e *MockWalletServiceInterface_Expecter) Withdraw(ctx interface{}, userID interface{}, req interface{}) *MockWalletServiceInterface_Withdraw_Call {
	return &MockWalletServiceInterface_Withdraw_Call{Call: _e.mock.On("Withdraw", ctx, userID, req)}
}

func (_c *MockWalletServiceInterface_Withdraw_Call) Run(run func(ctx context.Context, userID uuid.UUID, req WithdrawRequest)) *MockWalletServiceInterface_Withdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(WithdrawRequest))
	})
	return _c
}

func (_c *MockWalletServiceInterface_Withdraw_Call) Return(_a0 error) *MockWalletServiceInterface_Withdraw_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWalletServiceInterface_Withdraw_Call) RunAndReturn(run func(context.Context, uuid.UUID, WithdrawRequest) error) *MockWalletServiceInterface_Withdraw_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWalletServiceInterface creates a new instance of MockWalletServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletServiceInterface {
	mock := &MockWalletServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
