// Code generated by mockery v2.53.6. DO NOT EDIT.

package auth

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockFirebaseAuthClient is an autogenerated mock type for the FirebaseAuthClient type
type MockFirebaseAuthClient struct {
	mock.Mock
}

type MockFirebaseAuthClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFirebaseAuthClient) EXPECT() *MockFirebaseAuthClient_Expecter {
	return &MockFirebaseAuthClient_Expecter{mock: &_m.Mock}
}

// VerifyIDToken provides a mock function with given fields: ctx, idToken
func (_m *MockFirebaseAuthClient) VerifyIDToken(ctx context.Context, idToken string) (*FirebaseTokenResult, error) {
	ret := _m.Called(ctx, idToken)

	if len(ret) == 0 {
		panic("no return value specified for VerifyIDToken")
	}

	var r0 *FirebaseTokenResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*FirebaseTokenResult, error)); ok {
		return rf(ctx, idToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *FirebaseTokenResult); ok {
		r0 = rf(ctx, idToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*FirebaseTokenResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, idToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFirebaseAuthClient_VerifyIDToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyIDToken'
type MockFirebaseAuthClient_VerifyIDToken_Call struct {
	*mock.Call
}

// VerifyIDToken is a helper method to define mock.On call
//   - ctx context.Context
//   - idToken string
func (_e *MockFirebaseAuthClient_Expecter) VerifyIDToken(ctx interface{}, idToken interface{}) *MockFirebaseAuthClient_VerifyIDToken_Call {
	return &MockFirebaseAuthClient_VerifyIDToken_Call{Call: _e.mock.On("VerifyIDToken", ctx, idToken)}
}

func (_c *MockFirebaseAuthClient_VerifyIDToken_Call) Run(run func(ctx context.Context, idToken string)) *MockFirebaseAuthClient_VerifyIDToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockFirebaseAuthClient_VerifyIDToken_Call) Return(_a0 *FirebaseTokenResult, _a1 error) *MockFirebaseAuthClient_VerifyIDToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFirebaseAuthClient_VerifyIDToken_Call) RunAndReturn(run func(context.Context, string) (*FirebaseTokenResult, error)) *MockFirebaseAuthClient_VerifyIDToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFirebaseAuthClient creates a new instance of MockFirebaseAuthClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFirebaseAuthClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFirebaseAuthClient {
	mock := &MockFirebaseAuthClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
