// Code generated by mockery v2.53.6. DO NOT EDIT.

package auth

import (
	context "context"
	domain "go-shop-yourself/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRefreshTokenRepository is an autogenerated mock type for the RefreshTokenRepository type
type MockRefreshTokenRepository struct {
	mock.Mock
}

type MockRefreshTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepository_Expecter {
	return &MockRefreshTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, rt
func (_m *MockRefreshTokenRepository) Create(ctx context.Context, rt *domain.RefreshToken) error {
	ret := _m.Called(ctx, rt)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.RefreshToken) error); ok {
		r0 = rf(ctx, rt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRefreshTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - rt *domain.RefreshToken
func (_e *MockRefreshTokenRepository_Expecter) Create(ctx interface{}, rt interface{}) *MockRefreshTokenRepository_Create_Call {
	return &MockRefreshTokenRepository_Create_Call{Call: _e.mock.On("Create", ctx, rt)}
}

func (_c *MockRefreshTokenRepository_Create_Call) Run(run func(ctx context.Context, rt *domain.RefreshToken)) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.RefreshToken))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_Create_Call) Return(_a0 error) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.RefreshToken) error) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpiredTokens provides a mock function with given fields: ctx
func (_m *MockRefreshTokenRepository) DeleteExpiredTokens(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpiredTokens")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_DeleteExpiredTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpiredTokens'
type MockRefreshTokenRepository_DeleteExpiredTokens_Call struct {
	*mock.Call
}

// DeleteExpiredTokens is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRefreshTokenRepository_Expecter) DeleteExpiredTokens(ctx interface{}) *MockRefreshTokenRepository_DeleteExpiredTokens_Call {
	return &MockRefreshTokenRepository_DeleteExpiredTokens_Call{Call: _e.mock.On("DeleteExpiredTokens", ctx)}
}

func (_c *MockRefreshTokenRepository_DeleteExpiredTokens_Call) Run(run func(ctx context.Context)) *MockRefreshTokenRepository_DeleteExpiredTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteExpiredTokens_Call) Return(_a0 error) *MockRefreshTokenRepository_DeleteExpiredTokens_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteExpiredTokens_Call) RunAndReturn(run func(context.Context) error) *MockRefreshTokenRepository_DeleteExpiredTokens_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTokenHash provides a mock function with given fields: ctx, hash
func (_m *MockRefreshTokenRepository) GetByTokenHash(ctx context.Context, hash string) (*domain.RefreshToken, error) {
	ret := _m.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetByTokenHash")
	}

	var r0 *domain.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.RefreshToken, error)); ok {
		return rf(ctx, hash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.RefreshToken); ok {
		r0 = rf(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefreshTokenRepository_GetByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTokenHash'
type MockRefreshTokenRepository_GetByTokenHash_Call struct {
	*mock.Call
}

// GetByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockRefreshTokenRepository_Expecter) GetByTokenHash(ctx interface{}, hash interface{}) *MockRefreshTokenRepository_GetByTokenHash_Call {
	return &MockRefreshTokenRepository_GetByTokenHash_Call{Call: _e.mock.On("GetByTokenHash", ctx, hash)}
}

func (_c *MockRefreshTokenRepository_GetByTokenHash_Call) Run(run func(ctx context.Context, hash string)) *MockRefreshTokenRepository_GetByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_GetByTokenHash_Call) Return(_a0 *domain.RefreshToken, _a1 error) *MockRefreshTokenRepository_GetByTokenHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefreshTokenRepository_GetByTokenHash_Call) RunAndReturn(run func(context.Context, string) (*domain.RefreshToken, error)) *MockRefreshTokenRepository_GetByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllByFamilyID provides a mock function with given fields: ctx, familyID
func (_m *MockRefreshTokenRepository) RevokeAllByFamilyID(ctx context.Context, familyID uuid.UUID) error {
	ret := _m.Called(ctx, familyID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllByFamilyID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, familyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_RevokeAllByFamilyID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllByFamilyID'
type MockRefreshTokenRepository_RevokeAllByFamilyID_Call struct {
	*mock.Call
}

// RevokeAllByFamilyID is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID uuid.UUID
func (_e *MockRefreshTokenRepository_Expecter) RevokeAllByFamilyID(ctx interface{}, familyID interface{}) *MockRefreshTokenRepository_RevokeAllByFamilyID_Call {
	return &MockRefreshTokenRepository_RevokeAllByFamilyID_Call{Call: _e.mock.On("RevokeAllByFamilyID", ctx, familyID)}
}

func (_c *MockRefreshTokenRepository_RevokeAllByFamilyID_Call) Run(run func(ctx context.Context, familyID uuid.UUID)) *MockRefreshTokenRepository_RevokeAllByFamilyID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeAllByFamilyID_Call) Return(_a0 error) *MockRefreshTokenRepository_RevokeAllByFamilyID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeAllByFamilyID_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockRefreshTokenRepository_RevokeAllByFamilyID_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeByID provides a mock function with given fields: ctx, id
func (_m *MockRefreshTokenRepository) RevokeByID(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_RevokeByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeByID'
type MockRefreshTokenRepository_RevokeByID_Call struct {
	*mock.Call
}

// RevokeByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRefreshTokenRepository_Expecter) RevokeByID(ctx interface{}, id interface{}) *MockRefreshTokenRepository_RevokeByID_Call {
	return &MockRefreshTokenRepository_RevokeByID_Call{Call: _e.mock.On("RevokeByID", ctx, id)}
}

func (_c *MockRefreshTokenRepository_RevokeByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRefreshTokenRepository_RevokeByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeByID_Call) Return(_a0 error) *MockRefreshTokenRepository_RevokeByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockRefreshTokenRepository_RevokeByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefreshTokenRepository creates a new instance of MockRefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
