// Code generated by mockery v2.53.6. DO NOT EDIT.

package auth

import (
	context "context"
	domain "go-marketplace/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockVerificationRepository is an autogenerated mock type for the VerificationRepository type
type MockVerificationRepository struct {
	mock.Mock
}

type MockVerificationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVerificationRepository) EXPECT() *MockVerificationRepository_Expecter {
	return &MockVerificationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, vc
func (_m *MockVerificationRepository) Create(ctx context.Context, vc *domain.VerificationCode) error {
	ret := _m.Called(ctx, vc)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.VerificationCode) error); ok {
		r0 = rf(ctx, vc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVerificationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockVerificationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - vc *domain.VerificationCode
func (_e *MockVerificationRepository_Expecter) Create(ctx interface{}, vc interface{}) *MockVerificationRepository_Create_Call {
	return &MockVerificationRepository_Create_Call{Call: _e.mock.On("Create", ctx, vc)}
}

func (_c *MockVerificationRepository_Create_Call) Run(run func(ctx context.Context, vc *domain.VerificationCode)) *MockVerificationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.VerificationCode))
	})
	return _c
}

func (_c *MockVerificationRepository_Create_Call) Return(_a0 error) *MockVerificationRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVerificationRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.VerificationCode) error) *MockVerificationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUserID provides a mock function with given fields: ctx, userID
func (_m *MockVerificationRepository) DeleteByUserID(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVerificationRepository_DeleteByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUserID'
type MockVerificationRepository_DeleteByUserID_Call struct {
	*mock.Call
}

// DeleteByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockVerificationRepository_Expecter) DeleteByUserID(ctx interface{}, userID interface{}) *MockVerificationRepository_DeleteByUserID_Call {
	return &MockVerificationRepository_DeleteByUserID_Call{Call: _e.mock.On("DeleteByUserID", ctx, userID)}
}

func (_c *MockVerificationRepository_DeleteByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockVerificationRepository_DeleteByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockVerificationRepository_DeleteByUserID_Call) Return(_a0 error) *MockVerificationRepository_DeleteByUserID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVerificationRepository_DeleteByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockVerificationRepository_DeleteByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *MockVerificationRepository) GetByUserID(ctx context.Context, userID uuid.UUID) (*domain.VerificationCode, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 *domain.VerificationCode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.VerificationCode, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.VerificationCode); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.VerificationCode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVerificationRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockVerificationRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockVerificationRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *MockVerificationRepository_GetByUserID_Call {
	return &MockVerificationRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MockVerificationRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockVerificationRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockVerificationRepository_GetByUserID_Call) Return(_a0 *domain.VerificationCode, _a1 error) *MockVerificationRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVerificationRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.VerificationCode, error)) *MockVerificationRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVerificationRepository creates a new instance of MockVerificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVerificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVerificationRepository {
	mock := &MockVerificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
