// Code generated by mockery v2.53.6. DO NOT EDIT.

package auth

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSupabaseAuthClient is an autogenerated mock type for the SupabaseAuthClient type
type MockSupabaseAuthClient struct {
	mock.Mock
}

type MockSupabaseAuthClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSupabaseAuthClient) EXPECT() *MockSupabaseAuthClient_Expecter {
	return &MockSupabaseAuthClient_Expecter{mock: &_m.Mock}
}

// VerifyAccessToken provides a mock function with given fields: ctx, accessToken
func (_m *MockSupabaseAuthClient) VerifyAccessToken(ctx context.Context, accessToken string) (*SupabaseTokenResult, error) {
	ret := _m.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for VerifyAccessToken")
	}

	var r0 *SupabaseTokenResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*SupabaseTokenResult, error)); ok {
		return rf(ctx, accessToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *SupabaseTokenResult); ok {
		r0 = rf(ctx, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SupabaseTokenResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSupabaseAuthClient_VerifyAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyAccessToken'
type MockSupabaseAuthClient_VerifyAccessToken_Call struct {
	*mock.Call
}

// VerifyAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *MockSupabaseAuthClient_Expecter) VerifyAccessToken(ctx interface{}, accessToken interface{}) *MockSupabaseAuthClient_VerifyAccessToken_Call {
	return &MockSupabaseAuthClient_VerifyAccessToken_Call{Call: _e.mock.On("VerifyAccessToken", ctx, accessToken)}
}

func (_c *MockSupabaseAuthClient_VerifyAccessToken_Call) Run(run func(ctx context.Context, accessToken string)) *MockSupabaseAuthClient_VerifyAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSupabaseAuthClient_VerifyAccessToken_Call) Return(_a0 *SupabaseTokenResult, _a1 error) *MockSupabaseAuthClient_VerifyAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSupabaseAuthClient_VerifyAccessToken_Call) RunAndReturn(run func(context.Context, string) (*SupabaseTokenResult, error)) *MockSupabaseAuthClient_VerifyAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSupabaseAuthClient creates a new instance of MockSupabaseAuthClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSupabaseAuthClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSupabaseAuthClient {
	mock := &MockSupabaseAuthClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
