// Code generated by mockery v2.53.6. DO NOT EDIT.

package auth

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockMailService is an autogenerated mock type for the MailService type
type MockMailService struct {
	mock.Mock
}

type MockMailService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMailService) EXPECT() *MockMailService_Expecter {
	return &MockMailService_Expecter{mock: &_m.Mock}
}

// SendVerificationCode provides a mock function with given fields: ctx, email, code
func (_m *MockMailService) SendVerificationCode(ctx context.Context, email string, code string) error {
	ret := _m.Called(ctx, email, code)

	if len(ret) == 0 {
		panic("no return value specified for SendVerificationCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, email, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMailService_SendVerificationCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendVerificationCode'
type MockMailService_SendVerificationCode_Call struct {
	*mock.Call
}

// SendVerificationCode is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - code string
func (_e *MockMailService_Expecter) SendVerificationCode(ctx interface{}, email interface{}, code interface{}) *MockMailService_SendVerificationCode_Call {
	return &MockMailService_SendVerificationCode_Call{Call: _e.mock.On("SendVerificationCode", ctx, email, code)}
}

func (_c *MockMailService_SendVerificationCode_Call) Run(run func(ctx context.Context, email string, code string)) *MockMailService_SendVerificationCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMailService_SendVerificationCode_Call) Return(_a0 error) *MockMailService_SendVerificationCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMailService_SendVerificationCode_Call) RunAndReturn(run func(context.Context, string, string) error) *MockMailService_SendVerificationCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMailService creates a new instance of MockMailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMailService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMailService {
	mock := &MockMailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
