// Code generated by mockery v2.53.6. DO NOT EDIT.

package auth

import (
	context "context"
	domain "go-marketplace/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockSessionRepository is an autogenerated mock type for the SessionRepository type
type MockSessionRepository struct {
	mock.Mock
}

type MockSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepository) EXPECT() *MockSessionRepository_Expecter {
	return &MockSessionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, session
func (_m *MockSessionRepository) Create(ctx context.Context, session *domain.Session) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Session) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSessionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - session *domain.Session
func (_e *MockSessionRepository_Expecter) Create(ctx interface{}, session interface{}) *MockSessionRepository_Create_Call {
	return &MockSessionRepository_Create_Call{Call: _e.mock.On("Create", ctx, session)}
}

func (_c *MockSessionRepository_Create_Call) Run(run func(ctx context.Context, session *domain.Session)) *MockSessionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Session))
	})
	return _c
}

func (_c *MockSessionRepository_Create_Call) Return(_a0 error) *MockSessionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Session) error) *MockSessionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpiredSessions provides a mock function with given fields: ctx
func (_m *MockSessionRepository) DeleteExpiredSessions(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpiredSessions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionRepository_DeleteExpiredSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpiredSessions'
type MockSessionRepository_DeleteExpiredSessions_Call struct {
	*mock.Call
}

// DeleteExpiredSessions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSessionRepository_Expecter) DeleteExpiredSessions(ctx interface{}) *MockSessionRepository_DeleteExpiredSessions_Call {
	return &MockSessionRepository_DeleteExpiredSessions_Call{Call: _e.mock.On("DeleteExpiredSessions", ctx)}
}

func (_c *MockSessionRepository_DeleteExpiredSessions_Call) Run(run func(ctx context.Context)) *MockSessionRepository_DeleteExpiredSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSessionRepository_DeleteExpiredSessions_Call) Return(_a0 error) *MockSessionRepository_DeleteExpiredSessions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionRepository_DeleteExpiredSessions_Call) RunAndReturn(run func(context.Context) error) *MockSessionRepository_DeleteExpiredSessions_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTokenHash provides a mock function with given fields: ctx, hash
func (_m *MockSessionRepository) GetByTokenHash(ctx context.Context, hash string) (*domain.Session, error) {
	ret := _m.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetByTokenHash")
	}

	var r0 *domain.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Session, error)); ok {
		return rf(ctx, hash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Session); ok {
		r0 = rf(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionRepository_GetByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTokenHash'
type MockSessionRepository_GetByTokenHash_Call struct {
	*mock.Call
}

// GetByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockSessionRepository_Expecter) GetByTokenHash(ctx interface{}, hash interface{}) *MockSessionRepository_GetByTokenHash_Call {
	return &MockSessionRepository_GetByTokenHash_Call{Call: _e.mock.On("GetByTokenHash", ctx, hash)}
}

func (_c *MockSessionRepository_GetByTokenHash_Call) Run(run func(ctx context.Context, hash string)) *MockSessionRepository_GetByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionRepository_GetByTokenHash_Call) Return(_a0 *domain.Session, _a1 error) *MockSessionRepository_GetByTokenHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionRepository_GetByTokenHash_Call) RunAndReturn(run func(context.Context, string) (*domain.Session, error)) *MockSessionRepository_GetByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllByFamilyID provides a mock function with given fields: ctx, familyID
func (_m *MockSessionRepository) RevokeAllByFamilyID(ctx context.Context, familyID uuid.UUID) error {
	ret := _m.Called(ctx, familyID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllByFamilyID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, familyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionRepository_RevokeAllByFamilyID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllByFamilyID'
type MockSessionRepository_RevokeAllByFamilyID_Call struct {
	*mock.Call
}

// RevokeAllByFamilyID is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID uuid.UUID
func (_e *MockSessionRepository_Expecter) RevokeAllByFamilyID(ctx interface{}, familyID interface{}) *MockSessionRepository_RevokeAllByFamilyID_Call {
	return &MockSessionRepository_RevokeAllByFamilyID_Call{Call: _e.mock.On("RevokeAllByFamilyID", ctx, familyID)}
}

func (_c *MockSessionRepository_RevokeAllByFamilyID_Call) Run(run func(ctx context.Context, familyID uuid.UUID)) *MockSessionRepository_RevokeAllByFamilyID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSessionRepository_RevokeAllByFamilyID_Call) Return(_a0 error) *MockSessionRepository_RevokeAllByFamilyID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionRepository_RevokeAllByFamilyID_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockSessionRepository_RevokeAllByFamilyID_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeByID provides a mock function with given fields: ctx, id
func (_m *MockSessionRepository) RevokeByID(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionRepository_RevokeByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeByID'
type MockSessionRepository_RevokeByID_Call struct {
	*mock.Call
}

// RevokeByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSessionRepository_Expecter) RevokeByID(ctx interface{}, id interface{}) *MockSessionRepository_RevokeByID_Call {
	return &MockSessionRepository_RevokeByID_Call{Call: _e.mock.On("RevokeByID", ctx, id)}
}

func (_c *MockSessionRepository_RevokeByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSessionRepository_RevokeByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSessionRepository_RevokeByID_Call) Return(_a0 error) *MockSessionRepository_RevokeByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionRepository_RevokeByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockSessionRepository_RevokeByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionRepository creates a new instance of MockSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepository {
	mock := &MockSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
