// Code generated by mockery v2.53.6. DO NOT EDIT.

package auth

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockAuthServiceInterface is an autogenerated mock type for the AuthServiceInterface type
type MockAuthServiceInterface struct {
	mock.Mock
}

type MockAuthServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthServiceInterface) EXPECT() *MockAuthServiceInterface_Expecter {
	return &MockAuthServiceInterface_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, email, password, ipAddress, userAgent
func (_m *MockAuthServiceInterface) Login(ctx context.Context, email string, password string, ipAddress string, userAgent string) (*AuthResponse, error) {
	ret := _m.Called(ctx, email, password, ipAddress, userAgent)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*AuthResponse, error)); ok {
		return rf(ctx, email, password, ipAddress, userAgent)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *AuthResponse); ok {
		r0 = rf(ctx, email, password, ipAddress, userAgent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, email, password, ipAddress, userAgent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServiceInterface_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthServiceInterface_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
//   - ipAddress string
//   - userAgent string
func (_e *MockAuthServiceInterface_Expecter) Login(ctx interface{}, email interface{}, password interface{}, ipAddress interface{}, userAgent interface{}) *MockAuthServiceInterface_Login_Call {
	return &MockAuthServiceInterface_Login_Call{Call: _e.mock.On("Login", ctx, email, password, ipAddress, userAgent)}
}

func (_c *MockAuthServiceInterface_Login_Call) Run(run func(ctx context.Context, email string, password string, ipAddress string, userAgent string)) *MockAuthServiceInterface_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockAuthServiceInterface_Login_Call) Return(_a0 *AuthResponse, _a1 error) *MockAuthServiceInterface_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServiceInterface_Login_Call) RunAndReturn(run func(context.Context, string, string, string, string) (*AuthResponse, error)) *MockAuthServiceInterface_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, rawToken
func (_m *MockAuthServiceInterface) Logout(ctx context.Context, rawToken string) error {
	ret := _m.Called(ctx, rawToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, rawToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthServiceInterface_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthServiceInterface_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - rawToken string
func (_e *MockAuthServiceInterface_Expecter) Logout(ctx interface{}, rawToken interface{}) *MockAuthServiceInterface_Logout_Call {
	return &MockAuthServiceInterface_Logout_Call{Call: _e.mock.On("Logout", ctx, rawToken)}
}

func (_c *MockAuthServiceInterface_Logout_Call) Run(run func(ctx context.Context, rawToken string)) *MockAuthServiceInterface_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthServiceInterface_Logout_Call) Return(_a0 error) *MockAuthServiceInterface_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthServiceInterface_Logout_Call) RunAndReturn(run func(context.Context, string) error) *MockAuthServiceInterface_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshTokens provides a mock function with given fields: ctx, rawToken, ipAddress, userAgent
func (_m *MockAuthServiceInterface) RefreshTokens(ctx context.Context, rawToken string, ipAddress string, userAgent string) (*AuthResponse, error) {
	ret := _m.Called(ctx, rawToken, ipAddress, userAgent)

	if len(ret) == 0 {
		panic("no return value specified for RefreshTokens")
	}

	var r0 *AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*AuthResponse, error)); ok {
		return rf(ctx, rawToken, ipAddress, userAgent)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *AuthResponse); ok {
		r0 = rf(ctx, rawToken, ipAddress, userAgent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, rawToken, ipAddress, userAgent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServiceInterface_RefreshTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshTokens'
type MockAuthServiceInterface_RefreshTokens_Call struct {
	*mock.Call
}

// RefreshTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - rawToken string
//   - ipAddress string
//   - userAgent string
func (_e *MockAuthServiceInterface_Expecter) RefreshTokens(ctx interface{}, rawToken interface{}, ipAddress interface{}, userAgent interface{}) *MockAuthServiceInterface_RefreshTokens_Call {
	return &MockAuthServiceInterface_RefreshTokens_Call{Call: _e.mock.On("RefreshTokens", ctx, rawToken, ipAddress, userAgent)}
}

func (_c *MockAuthServiceInterface_RefreshTokens_Call) Run(run func(ctx context.Context, rawToken string, ipAddress string, userAgent string)) *MockAuthServiceInterface_RefreshTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockAuthServiceInterface_RefreshTokens_Call) Return(_a0 *AuthResponse, _a1 error) *MockAuthServiceInterface_RefreshTokens_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServiceInterface_RefreshTokens_Call) RunAndReturn(run func(context.Context, string, string, string) (*AuthResponse, error)) *MockAuthServiceInterface_RefreshTokens_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, fullName, email, password, username
func (_m *MockAuthServiceInterface) Register(ctx context.Context, fullName string, email string, password string, username string) (*AuthResponse, error) {
	ret := _m.Called(ctx, fullName, email, password, username)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*AuthResponse, error)); ok {
		return rf(ctx, fullName, email, password, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *AuthResponse); ok {
		r0 = rf(ctx, fullName, email, password, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, fullName, email, password, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServiceInterface_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthServiceInterface_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - fullName string
//   - email string
//   - password string
//   - username string
func (_e *MockAuthServiceInterface_Expecter) Register(ctx interface{}, fullName interface{}, email interface{}, password interface{}, username interface{}) *MockAuthServiceInterface_Register_Call {
	return &MockAuthServiceInterface_Register_Call{Call: _e.mock.On("Register", ctx, fullName, email, password, username)}
}

func (_c *MockAuthServiceInterface_Register_Call) Run(run func(ctx context.Context, fullName string, email string, password string, username string)) *MockAuthServiceInterface_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockAuthServiceInterface_Register_Call) Return(_a0 *AuthResponse, _a1 error) *MockAuthServiceInterface_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServiceInterface_Register_Call) RunAndReturn(run func(context.Context, string, string, string, string) (*AuthResponse, error)) *MockAuthServiceInterface_Register_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyEmail provides a mock function with given fields: ctx, userID, code
func (_m *MockAuthServiceInterface) VerifyEmail(ctx context.Context, userID uuid.UUID, code string) error {
	ret := _m.Called(ctx, userID, code)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, userID, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthServiceInterface_VerifyEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyEmail'
type MockAuthServiceInterface_VerifyEmail_Call struct {
	*mock.Call
}

// VerifyEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - code string
func (_e *MockAuthServiceInterface_Expecter) VerifyEmail(ctx interface{}, userID interface{}, code interface{}) *MockAuthServiceInterface_VerifyEmail_Call {
	return &MockAuthServiceInterface_VerifyEmail_Call{Call: _e.mock.On("VerifyEmail", ctx, userID, code)}
}

func (_c *MockAuthServiceInterface_VerifyEmail_Call) Run(run func(ctx context.Context, userID uuid.UUID, code string)) *MockAuthServiceInterface_VerifyEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockAuthServiceInterface_VerifyEmail_Call) Return(_a0 error) *MockAuthServiceInterface_VerifyEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthServiceInterface_VerifyEmail_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockAuthServiceInterface_VerifyEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthServiceInterface creates a new instance of MockAuthServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthServiceInterface {
	mock := &MockAuthServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
