// Code generated by mockery v2.53.6. DO NOT EDIT.

package user

import (
	context "context"
	domain "go-shop-yourself/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// CreateAddress provides a mock function with given fields: ctx, addr
func (_m *MockUserRepository) CreateAddress(ctx context.Context, addr *domain.UserAddress) error {
	ret := _m.Called(ctx, addr)

	if len(ret) == 0 {
		panic("no return value specified for CreateAddress")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserAddress) error); ok {
		r0 = rf(ctx, addr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_CreateAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAddress'
type MockUserRepository_CreateAddress_Call struct {
	*mock.Call
}

// CreateAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - addr *domain.UserAddress
func (_e *MockUserRepository_Expecter) CreateAddress(ctx interface{}, addr interface{}) *MockUserRepository_CreateAddress_Call {
	return &MockUserRepository_CreateAddress_Call{Call: _e.mock.On("CreateAddress", ctx, addr)}
}

func (_c *MockUserRepository_CreateAddress_Call) Run(run func(ctx context.Context, addr *domain.UserAddress)) *MockUserRepository_CreateAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.UserAddress))
	})
	return _c
}

func (_c *MockUserRepository_CreateAddress_Call) Return(_a0 error) *MockUserRepository_CreateAddress_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_CreateAddress_Call) RunAndReturn(run func(context.Context, *domain.UserAddress) error) *MockUserRepository_CreateAddress_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, u
func (_m *MockUserRepository) CreateUser(ctx context.Context, u *domain.User) error {
	ret := _m.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - u *domain.User
func (_e *MockUserRepository_Expecter) CreateUser(ctx interface{}, u interface{}) *MockUserRepository_CreateUser_Call {
	return &MockUserRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, u)}
}

func (_c *MockUserRepository_CreateUser_Call) Run(run func(ctx context.Context, u *domain.User)) *MockUserRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.User))
	})
	return _c
}

func (_c *MockUserRepository_CreateUser_Call) Return(_a0 error) *MockUserRepository_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_CreateUser_Call) RunAndReturn(run func(context.Context, *domain.User) error) *MockUserRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAddress provides a mock function with given fields: ctx, addressID
func (_m *MockUserRepository) DeleteAddress(ctx context.Context, addressID uuid.UUID) error {
	ret := _m.Called(ctx, addressID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAddress")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, addressID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_DeleteAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAddress'
type MockUserRepository_DeleteAddress_Call struct {
	*mock.Call
}

// DeleteAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - addressID uuid.UUID
func (_e *MockUserRepository_Expecter) DeleteAddress(ctx interface{}, addressID interface{}) *MockUserRepository_DeleteAddress_Call {
	return &MockUserRepository_DeleteAddress_Call{Call: _e.mock.On("DeleteAddress", ctx, addressID)}
}

func (_c *MockUserRepository_DeleteAddress_Call) Run(run func(ctx context.Context, addressID uuid.UUID)) *MockUserRepository_DeleteAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserRepository_DeleteAddress_Call) Return(_a0 error) *MockUserRepository_DeleteAddress_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_DeleteAddress_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockUserRepository_DeleteAddress_Call {
	_c.Call.Return(run)
	return _c
}

// GetAddressByID provides a mock function with given fields: ctx, addressID
func (_m *MockUserRepository) GetAddressByID(ctx context.Context, addressID uuid.UUID) (*domain.UserAddress, error) {
	ret := _m.Called(ctx, addressID)

	if len(ret) == 0 {
		panic("no return value specified for GetAddressByID")
	}

	var r0 *domain.UserAddress
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.UserAddress, error)); ok {
		return rf(ctx, addressID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.UserAddress); ok {
		r0 = rf(ctx, addressID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserAddress)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, addressID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetAddressByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAddressByID'
type MockUserRepository_GetAddressByID_Call struct {
	*mock.Call
}

// GetAddressByID is a helper method to define mock.On call
//   - ctx context.Context
//   - addressID uuid.UUID
func (_e *MockUserRepository_Expecter) GetAddressByID(ctx interface{}, addressID interface{}) *MockUserRepository_GetAddressByID_Call {
	return &MockUserRepository_GetAddressByID_Call{Call: _e.mock.On("GetAddressByID", ctx, addressID)}
}

func (_c *MockUserRepository_GetAddressByID_Call) Run(run func(ctx context.Context, addressID uuid.UUID)) *MockUserRepository_GetAddressByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserRepository_GetAddressByID_Call) Return(_a0 *domain.UserAddress, _a1 error) *MockUserRepository_GetAddressByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetAddressByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.UserAddress, error)) *MockUserRepository_GetAddressByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAddressesByUserID provides a mock function with given fields: ctx, userID
func (_m *MockUserRepository) GetAddressesByUserID(ctx context.Context, userID uuid.UUID) ([]domain.UserAddress, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAddressesByUserID")
	}

	var r0 []domain.UserAddress
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.UserAddress, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.UserAddress); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UserAddress)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetAddressesByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAddressesByUserID'
type MockUserRepository_GetAddressesByUserID_Call struct {
	*mock.Call
}

// GetAddressesByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUserRepository_Expecter) GetAddressesByUserID(ctx interface{}, userID interface{}) *MockUserRepository_GetAddressesByUserID_Call {
	return &MockUserRepository_GetAddressesByUserID_Call{Call: _e.mock.On("GetAddressesByUserID", ctx, userID)}
}

func (_c *MockUserRepository_GetAddressesByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUserRepository_GetAddressesByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserRepository_GetAddressesByUserID_Call) Return(_a0 []domain.UserAddress, _a1 error) *MockUserRepository_GetAddressesByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetAddressesByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]domain.UserAddress, error)) *MockUserRepository_GetAddressesByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *MockUserRepository) GetUserByEmail(ctx context.Context, email string) (*domain.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockUserRepository_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepository_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *MockUserRepository_GetUserByEmail_Call {
	return &MockUserRepository_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockUserRepository_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepository_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_GetUserByEmail_Call) Return(_a0 *domain.User, _a1 error) *MockUserRepository_GetUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetUserByEmail_Call) RunAndReturn(run func(context.Context, string) (*domain.User, error)) *MockUserRepository_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, id
func (_m *MockUserRepository) GetUserByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserRepository_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserRepository_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockUserRepository_GetUserByID_Call {
	return &MockUserRepository_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockUserRepository_GetUserByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserRepository_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserRepository_GetUserByID_Call) Return(_a0 *domain.User, _a1 error) *MockUserRepository_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetUserByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.User, error)) *MockUserRepository_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByProviderID provides a mock function with given fields: ctx, provider, providerID
func (_m *MockUserRepository) GetUserByProviderID(ctx context.Context, provider string, providerID string) (*domain.User, error) {
	ret := _m.Called(ctx, provider, providerID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByProviderID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, error)); ok {
		return rf(ctx, provider, providerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = rf(ctx, provider, providerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, provider, providerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetUserByProviderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByProviderID'
type MockUserRepository_GetUserByProviderID_Call struct {
	*mock.Call
}

// GetUserByProviderID is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - providerID string
func (_e *MockUserRepository_Expecter) GetUserByProviderID(ctx interface{}, provider interface{}, providerID interface{}) *MockUserRepository_GetUserByProviderID_Call {
	return &MockUserRepository_GetUserByProviderID_Call{Call: _e.mock.On("GetUserByProviderID", ctx, provider, providerID)}
}

func (_c *MockUserRepository_GetUserByProviderID_Call) Run(run func(ctx context.Context, provider string, providerID string)) *MockUserRepository_GetUserByProviderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserRepository_GetUserByProviderID_Call) Return(_a0 *domain.User, _a1 error) *MockUserRepository_GetUserByProviderID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetUserByProviderID_Call) RunAndReturn(run func(context.Context, string, string) (*domain.User, error)) *MockUserRepository_GetUserByProviderID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUsername provides a mock function with given fields: ctx, username
func (_m *MockUserRepository) GetUserByUsername(ctx context.Context, username string) (*domain.User, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsername")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUsername'
type MockUserRepository_GetUserByUsername_Call struct {
	*mock.Call
}

// GetUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserRepository_Expecter) GetUserByUsername(ctx interface{}, username interface{}) *MockUserRepository_GetUserByUsername_Call {
	return &MockUserRepository_GetUserByUsername_Call{Call: _e.mock.On("GetUserByUsername", ctx, username)}
}

func (_c *MockUserRepository_GetUserByUsername_Call) Run(run func(ctx context.Context, username string)) *MockUserRepository_GetUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_GetUserByUsername_Call) Return(_a0 *domain.User, _a1 error) *MockUserRepository_GetUserByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetUserByUsername_Call) RunAndReturn(run func(context.Context, string) (*domain.User, error)) *MockUserRepository_GetUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// UnsetDefaultAddresses provides a mock function with given fields: ctx, userID
func (_m *MockUserRepository) UnsetDefaultAddresses(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for UnsetDefaultAddresses")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_UnsetDefaultAddresses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnsetDefaultAddresses'
type MockUserRepository_UnsetDefaultAddresses_Call struct {
	*mock.Call
}

// UnsetDefaultAddresses is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUserRepository_Expecter) UnsetDefaultAddresses(ctx interface{}, userID interface{}) *MockUserRepository_UnsetDefaultAddresses_Call {
	return &MockUserRepository_UnsetDefaultAddresses_Call{Call: _e.mock.On("UnsetDefaultAddresses", ctx, userID)}
}

func (_c *MockUserRepository_UnsetDefaultAddresses_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUserRepository_UnsetDefaultAddresses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserRepository_UnsetDefaultAddresses_Call) Return(_a0 error) *MockUserRepository_UnsetDefaultAddresses_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_UnsetDefaultAddresses_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockUserRepository_UnsetDefaultAddresses_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAddress provides a mock function with given fields: ctx, addr
func (_m *MockUserRepository) UpdateAddress(ctx context.Context, addr *domain.UserAddress) error {
	ret := _m.Called(ctx, addr)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAddress")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserAddress) error); ok {
		r0 = rf(ctx, addr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_UpdateAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAddress'
type MockUserRepository_UpdateAddress_Call struct {
	*mock.Call
}

// UpdateAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - addr *domain.UserAddress
func (_e *MockUserRepository_Expecter) UpdateAddress(ctx interface{}, addr interface{}) *MockUserRepository_UpdateAddress_Call {
	return &MockUserRepository_UpdateAddress_Call{Call: _e.mock.On("UpdateAddress", ctx, addr)}
}

func (_c *MockUserRepository_UpdateAddress_Call) Run(run func(ctx context.Context, addr *domain.UserAddress)) *MockUserRepository_UpdateAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.UserAddress))
	})
	return _c
}

func (_c *MockUserRepository_UpdateAddress_Call) Return(_a0 error) *MockUserRepository_UpdateAddress_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_UpdateAddress_Call) RunAndReturn(run func(context.Context, *domain.UserAddress) error) *MockUserRepository_UpdateAddress_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
