// Code generated by mockery v2.53.6. DO NOT EDIT.

package user

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// AddAddress provides a mock function with given fields: ctx, userID, req
func (_m *MockUserService) AddAddress(ctx context.Context, userID uuid.UUID, req *AddressRequest) (*AddressResponse, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for AddAddress")
	}

	var r0 *AddressResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *AddressRequest) (*AddressResponse, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *AddressRequest) *AddressResponse); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AddressResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *AddressRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_AddAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddAddress'
type MockUserService_AddAddress_Call struct {
	*mock.Call
}

// AddAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req *AddressRequest
func (_e *MockUserService_Expecter) AddAddress(ctx interface{}, userID interface{}, req interface{}) *MockUserService_AddAddress_Call {
	return &MockUserService_AddAddress_Call{Call: _e.mock.On("AddAddress", ctx, userID, req)}
}

func (_c *MockUserService_AddAddress_Call) Run(run func(ctx context.Context, userID uuid.UUID, req *AddressRequest)) *MockUserService_AddAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*AddressRequest))
	})
	return _c
}

func (_c *MockUserService_AddAddress_Call) Return(_a0 *AddressResponse, _a1 error) *MockUserService_AddAddress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_AddAddress_Call) RunAndReturn(run func(context.Context, uuid.UUID, *AddressRequest) (*AddressResponse, error)) *MockUserService_AddAddress_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAddress provides a mock function with given fields: ctx, userID, addressID
func (_m *MockUserService) DeleteAddress(ctx context.Context, userID uuid.UUID, addressID uuid.UUID) error {
	ret := _m.Called(ctx, userID, addressID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAddress")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, addressID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_DeleteAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAddress'
type MockUserService_DeleteAddress_Call struct {
	*mock.Call
}

// DeleteAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - addressID uuid.UUID
func (_e *MockUserService_Expecter) DeleteAddress(ctx interface{}, userID interface{}, addressID interface{}) *MockUserService_DeleteAddress_Call {
	return &MockUserService_DeleteAddress_Call{Call: _e.mock.On("DeleteAddress", ctx, userID, addressID)}
}

func (_c *MockUserService_DeleteAddress_Call) Run(run func(ctx context.Context, userID uuid.UUID, addressID uuid.UUID)) *MockUserService_DeleteAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserService_DeleteAddress_Call) Return(_a0 error) *MockUserService_DeleteAddress_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_DeleteAddress_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockUserService_DeleteAddress_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, id
func (_m *MockUserService) GetUserByID(ctx context.Context, id uuid.UUID) (*UserResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*UserResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *UserResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserService_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserService_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockUserService_GetUserByID_Call {
	return &MockUserService_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockUserService_GetUserByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserService_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserService_GetUserByID_Call) Return(_a0 *UserResponse, _a1 error) *MockUserService_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_GetUserByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*UserResponse, error)) *MockUserService_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListAddresses provides a mock function with given fields: ctx, userID
func (_m *MockUserService) ListAddresses(ctx context.Context, userID uuid.UUID) ([]AddressResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListAddresses")
	}

	var r0 []AddressResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]AddressResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []AddressResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]AddressResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_ListAddresses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAddresses'
type MockUserService_ListAddresses_Call struct {
	*mock.Call
}

// ListAddresses is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUserService_Expecter) ListAddresses(ctx interface{}, userID interface{}) *MockUserService_ListAddresses_Call {
	return &MockUserService_ListAddresses_Call{Call: _e.mock.On("ListAddresses", ctx, userID)}
}

func (_c *MockUserService_ListAddresses_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUserService_ListAddresses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserService_ListAddresses_Call) Return(_a0 []AddressResponse, _a1 error) *MockUserService_ListAddresses_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_ListAddresses_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]AddressResponse, error)) *MockUserService_ListAddresses_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAddress provides a mock function with given fields: ctx, userID, addressID, req
func (_m *MockUserService) UpdateAddress(ctx context.Context, userID uuid.UUID, addressID uuid.UUID, req *AddressRequest) (*AddressResponse, error) {
	ret := _m.Called(ctx, userID, addressID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAddress")
	}

	var r0 *AddressResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *AddressRequest) (*AddressResponse, error)); ok {
		return rf(ctx, userID, addressID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *AddressRequest) *AddressResponse); ok {
		r0 = rf(ctx, userID, addressID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AddressResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, *AddressRequest) error); ok {
		r1 = rf(ctx, userID, addressID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_UpdateAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAddress'
type MockUserService_UpdateAddress_Call struct {
	*mock.Call
}

// UpdateAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - addressID uuid.UUID
//   - req *AddressRequest
func (_e *MockUserService_Expecter) UpdateAddress(ctx interface{}, userID interface{}, addressID interface{}, req interface{}) *MockUserService_UpdateAddress_Call {
	return &MockUserService_UpdateAddress_Call{Call: _e.mock.On("UpdateAddress", ctx, userID, addressID, req)}
}

func (_c *MockUserService_UpdateAddress_Call) Run(run func(ctx context.Context, userID uuid.UUID, addressID uuid.UUID, req *AddressRequest)) *MockUserService_UpdateAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(*AddressRequest))
	})
	return _c
}

func (_c *MockUserService_UpdateAddress_Call) Return(_a0 *AddressResponse, _a1 error) *MockUserService_UpdateAddress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_UpdateAddress_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, *AddressRequest) (*AddressResponse, error)) *MockUserService_UpdateAddress_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
