package domain

import "errors"

var (
	ErrUserNotFound          = errors.New("user not found")
	ErrUserAlreadyExists     = errors.New("user already exists")
	ErrInvalidCredentials    = errors.New("invalid email or password")
	ErrMerchantNotFound      = errors.New("merchant not found")
	ErrMerchantAlreadyExists = errors.New("merchant already exists for this user")
	ErrProductNotFound       = errors.New("product not found")
	ErrWalletNotFound        = errors.New("wallet not found")
	ErrWalletAlreadyExists   = errors.New("wallet already exists for this user")
	ErrWalletNotActive       = errors.New("wallet is not active")
	ErrInsufficientBalance   = errors.New("insufficient balance")
	ErrInvalidRefreshToken   = errors.New("invalid refresh token")
	ErrRefreshTokenExpired   = errors.New("refresh token expired")
	ErrRefreshTokenReused    = errors.New("token reuse detected - all tokens in family revoked")

	ErrOrderNotFound            = errors.New("order not found")
	ErrOrderNotCancellable      = errors.New("order cannot be cancelled at this stage or time")
	ErrMerchantShipmentTooEarly = errors.New("shipment cannot be processed within 1 hour of order packaging")
	ErrInsufficientStock        = errors.New("insufficient product stock")
	ErrCartItemNotFound         = errors.New("cart item not found")
	ErrInvalidStatusTransition  = errors.New("invalid order status transition")
	ErrForbidden                = errors.New("forbidden: you do not have permission to access this resource")
	ErrAddressNotFound          = errors.New("address not found")
	ErrRecipientNameRequired    = errors.New("recipient name is required")
	ErrPhoneNumberRequired      = errors.New("phone number is required")
	ErrStreetAddressRequired    = errors.New("street address is required")
	ErrCityRequired             = errors.New("city is required")
	ErrProvinceRequired         = errors.New("province is required")
	ErrPostalCodeRequired       = errors.New("postal code is required")
	ErrInvalidAddressTag        = errors.New("invalid address tag")
)
