// Code generated by mockery v2.53.6. DO NOT EDIT.

package domain

import (
	context "context"
	sql "database/sql"

	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"
)

// MockPool is an autogenerated mock type for the Pool type
type MockPool struct {
	mock.Mock
}

type MockPool_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPool) EXPECT() *MockPool_Expecter {
	return &MockPool_Expecter{mock: &_m.Mock}
}

// BeginTxx provides a mock function with given fields: ctx, opts
func (_m *MockPool) BeginTxx(ctx context.Context, opts *sql.TxOptions) (*sqlx.Tx, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for BeginTxx")
	}

	var r0 *sqlx.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) (*sqlx.Tx, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) *sqlx.Tx); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlx.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sql.TxOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPool_BeginTxx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTxx'
type MockPool_BeginTxx_Call struct {
	*mock.Call
}

// BeginTxx is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *sql.TxOptions
func (_e *MockPool_Expecter) BeginTxx(ctx interface{}, opts interface{}) *MockPool_BeginTxx_Call {
	return &MockPool_BeginTxx_Call{Call: _e.mock.On("BeginTxx", ctx, opts)}
}

func (_c *MockPool_BeginTxx_Call) Run(run func(ctx context.Context, opts *sql.TxOptions)) *MockPool_BeginTxx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sql.TxOptions))
	})
	return _c
}

func (_c *MockPool_BeginTxx_Call) Return(_a0 *sqlx.Tx, _a1 error) *MockPool_BeginTxx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPool_BeginTxx_Call) RunAndReturn(run func(context.Context, *sql.TxOptions) (*sqlx.Tx, error)) *MockPool_BeginTxx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPool creates a new instance of MockPool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPool(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPool {
	mock := &MockPool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
