// Code generated by mockery v2.53.6. DO NOT EDIT.

package merchant

import (
	context "context"
	domain "go-shop-yourself/internal/domain"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"

	uuid "github.com/google/uuid"
)

// MockMerchantRepository is an autogenerated mock type for the MerchantRepository type
type MockMerchantRepository struct {
	mock.Mock
}

type MockMerchantRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMerchantRepository) EXPECT() *MockMerchantRepository_Expecter {
	return &MockMerchantRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, m
func (_m *MockMerchantRepository) Create(ctx context.Context, m *domain.Merchant) error {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Merchant) error); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMerchantRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMerchantRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - m *domain.Merchant
func (_e *MockMerchantRepository_Expecter) Create(ctx interface{}, m interface{}) *MockMerchantRepository_Create_Call {
	return &MockMerchantRepository_Create_Call{Call: _e.mock.On("Create", ctx, m)}
}

func (_c *MockMerchantRepository_Create_Call) Run(run func(ctx context.Context, m *domain.Merchant)) *MockMerchantRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Merchant))
	})
	return _c
}

func (_c *MockMerchantRepository_Create_Call) Return(_a0 error) *MockMerchantRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMerchantRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Merchant) error) *MockMerchantRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTx provides a mock function with given fields: ctx, tx, m
func (_m *MockMerchantRepository) CreateTx(ctx context.Context, tx pgx.Tx, m *domain.Merchant) error {
	ret := _m.Called(ctx, tx, m)

	if len(ret) == 0 {
		panic("no return value specified for CreateTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, *domain.Merchant) error); ok {
		r0 = rf(ctx, tx, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMerchantRepository_CreateTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTx'
type MockMerchantRepository_CreateTx_Call struct {
	*mock.Call
}

// CreateTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - m *domain.Merchant
func (_e *MockMerchantRepository_Expecter) CreateTx(ctx interface{}, tx interface{}, m interface{}) *MockMerchantRepository_CreateTx_Call {
	return &MockMerchantRepository_CreateTx_Call{Call: _e.mock.On("CreateTx", ctx, tx, m)}
}

func (_c *MockMerchantRepository_CreateTx_Call) Run(run func(ctx context.Context, tx pgx.Tx, m *domain.Merchant)) *MockMerchantRepository_CreateTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx), args[2].(*domain.Merchant))
	})
	return _c
}

func (_c *MockMerchantRepository_CreateTx_Call) Return(_a0 error) *MockMerchantRepository_CreateTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMerchantRepository_CreateTx_Call) RunAndReturn(run func(context.Context, pgx.Tx, *domain.Merchant) error) *MockMerchantRepository_CreateTx_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockMerchantRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Merchant, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Merchant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Merchant, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Merchant); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Merchant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMerchantRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockMerchantRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockMerchantRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockMerchantRepository_GetByID_Call {
	return &MockMerchantRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockMerchantRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockMerchantRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockMerchantRepository_GetByID_Call) Return(_a0 *domain.Merchant, _a1 error) *MockMerchantRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMerchantRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Merchant, error)) *MockMerchantRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *MockMerchantRepository) GetByUserID(ctx context.Context, userID uuid.UUID) (*domain.Merchant, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 *domain.Merchant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Merchant, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Merchant); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Merchant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMerchantRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockMerchantRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockMerchantRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *MockMerchantRepository_GetByUserID_Call {
	return &MockMerchantRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MockMerchantRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockMerchantRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockMerchantRepository_GetByUserID_Call) Return(_a0 *domain.Merchant, _a1 error) *MockMerchantRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMerchantRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Merchant, error)) *MockMerchantRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPool provides a mock function with no fields
func (_m *MockMerchantRepository) GetPool() domain.Pool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPool")
	}

	var r0 domain.Pool
	if rf, ok := ret.Get(0).(func() domain.Pool); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Pool)
		}
	}

	return r0
}

// MockMerchantRepository_GetPool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPool'
type MockMerchantRepository_GetPool_Call struct {
	*mock.Call
}

// GetPool is a helper method to define mock.On call
func (_e *MockMerchantRepository_Expecter) GetPool() *MockMerchantRepository_GetPool_Call {
	return &MockMerchantRepository_GetPool_Call{Call: _e.mock.On("GetPool")}
}

func (_c *MockMerchantRepository_GetPool_Call) Run(run func()) *MockMerchantRepository_GetPool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMerchantRepository_GetPool_Call) Return(_a0 domain.Pool) *MockMerchantRepository_GetPool_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMerchantRepository_GetPool_Call) RunAndReturn(run func() domain.Pool) *MockMerchantRepository_GetPool_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMerchantRepository creates a new instance of MockMerchantRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMerchantRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMerchantRepository {
	mock := &MockMerchantRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
