// Code generated by mockery v2.53.6. DO NOT EDIT.

package merchant

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockMerchantServiceInterface is an autogenerated mock type for the MerchantServiceInterface type
type MockMerchantServiceInterface struct {
	mock.Mock
}

type MockMerchantServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMerchantServiceInterface) EXPECT() *MockMerchantServiceInterface_Expecter {
	return &MockMerchantServiceInterface_Expecter{mock: &_m.Mock}
}

// RegisterMerchant provides a mock function with given fields: ctx, userID, req
func (_m *MockMerchantServiceInterface) RegisterMerchant(ctx context.Context, userID uuid.UUID, req MerchantRegisterRequest) (*MerchantResponse, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for RegisterMerchant")
	}

	var r0 *MerchantResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, MerchantRegisterRequest) (*MerchantResponse, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, MerchantRegisterRequest) *MerchantResponse); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MerchantResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, MerchantRegisterRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMerchantServiceInterface_RegisterMerchant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterMerchant'
type MockMerchantServiceInterface_RegisterMerchant_Call struct {
	*mock.Call
}

// RegisterMerchant is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req MerchantRegisterRequest
func (_e *MockMerchantServiceInterface_Expecter) RegisterMerchant(ctx interface{}, userID interface{}, req interface{}) *MockMerchantServiceInterface_RegisterMerchant_Call {
	return &MockMerchantServiceInterface_RegisterMerchant_Call{Call: _e.mock.On("RegisterMerchant", ctx, userID, req)}
}

func (_c *MockMerchantServiceInterface_RegisterMerchant_Call) Run(run func(ctx context.Context, userID uuid.UUID, req MerchantRegisterRequest)) *MockMerchantServiceInterface_RegisterMerchant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(MerchantRegisterRequest))
	})
	return _c
}

func (_c *MockMerchantServiceInterface_RegisterMerchant_Call) Return(_a0 *MerchantResponse, _a1 error) *MockMerchantServiceInterface_RegisterMerchant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMerchantServiceInterface_RegisterMerchant_Call) RunAndReturn(run func(context.Context, uuid.UUID, MerchantRegisterRequest) (*MerchantResponse, error)) *MockMerchantServiceInterface_RegisterMerchant_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMerchantServiceInterface creates a new instance of MockMerchantServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMerchantServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMerchantServiceInterface {
	mock := &MockMerchantServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
