// Code generated by mockery v2.53.6. DO NOT EDIT.

package cart

import (
	context "context"
	domain "go-shop-yourself/internal/domain"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"

	uuid "github.com/google/uuid"
)

// MockCartRepository is an autogenerated mock type for the CartRepository type
type MockCartRepository struct {
	mock.Mock
}

type MockCartRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCartRepository) EXPECT() *MockCartRepository_Expecter {
	return &MockCartRepository_Expecter{mock: &_m.Mock}
}

// ClearCart provides a mock function with given fields: ctx, userID
func (_m *MockCartRepository) ClearCart(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ClearCart")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCartRepository_ClearCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearCart'
type MockCartRepository_ClearCart_Call struct {
	*mock.Call
}

// ClearCart is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockCartRepository_Expecter) ClearCart(ctx interface{}, userID interface{}) *MockCartRepository_ClearCart_Call {
	return &MockCartRepository_ClearCart_Call{Call: _e.mock.On("ClearCart", ctx, userID)}
}

func (_c *MockCartRepository_ClearCart_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockCartRepository_ClearCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCartRepository_ClearCart_Call) Return(_a0 error) *MockCartRepository_ClearCart_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCartRepository_ClearCart_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockCartRepository_ClearCart_Call {
	_c.Call.Return(run)
	return _c
}

// ClearCartTX provides a mock function with given fields: ctx, tx, userID
func (_m *MockCartRepository) ClearCartTX(ctx context.Context, tx pgx.Tx, userID uuid.UUID) error {
	ret := _m.Called(ctx, tx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ClearCartTX")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, uuid.UUID) error); ok {
		r0 = rf(ctx, tx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCartRepository_ClearCartTX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearCartTX'
type MockCartRepository_ClearCartTX_Call struct {
	*mock.Call
}

// ClearCartTX is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - userID uuid.UUID
func (_e *MockCartRepository_Expecter) ClearCartTX(ctx interface{}, tx interface{}, userID interface{}) *MockCartRepository_ClearCartTX_Call {
	return &MockCartRepository_ClearCartTX_Call{Call: _e.mock.On("ClearCartTX", ctx, tx, userID)}
}

func (_c *MockCartRepository_ClearCartTX_Call) Run(run func(ctx context.Context, tx pgx.Tx, userID uuid.UUID)) *MockCartRepository_ClearCartTX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockCartRepository_ClearCartTX_Call) Return(_a0 error) *MockCartRepository_ClearCartTX_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCartRepository_ClearCartTX_Call) RunAndReturn(run func(context.Context, pgx.Tx, uuid.UUID) error) *MockCartRepository_ClearCartTX_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCartItem provides a mock function with given fields: ctx, userID, productID
func (_m *MockCartRepository) DeleteCartItem(ctx context.Context, userID uuid.UUID, productID uuid.UUID) error {
	ret := _m.Called(ctx, userID, productID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCartItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, productID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCartRepository_DeleteCartItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCartItem'
type MockCartRepository_DeleteCartItem_Call struct {
	*mock.Call
}

// DeleteCartItem is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - productID uuid.UUID
func (_e *MockCartRepository_Expecter) DeleteCartItem(ctx interface{}, userID interface{}, productID interface{}) *MockCartRepository_DeleteCartItem_Call {
	return &MockCartRepository_DeleteCartItem_Call{Call: _e.mock.On("DeleteCartItem", ctx, userID, productID)}
}

func (_c *MockCartRepository_DeleteCartItem_Call) Run(run func(ctx context.Context, userID uuid.UUID, productID uuid.UUID)) *MockCartRepository_DeleteCartItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockCartRepository_DeleteCartItem_Call) Return(_a0 error) *MockCartRepository_DeleteCartItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCartRepository_DeleteCartItem_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockCartRepository_DeleteCartItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetCartByUserID provides a mock function with given fields: ctx, userID
func (_m *MockCartRepository) GetCartByUserID(ctx context.Context, userID uuid.UUID) ([]domain.CartItem, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCartByUserID")
	}

	var r0 []domain.CartItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.CartItem, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.CartItem); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.CartItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCartRepository_GetCartByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCartByUserID'
type MockCartRepository_GetCartByUserID_Call struct {
	*mock.Call
}

// GetCartByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockCartRepository_Expecter) GetCartByUserID(ctx interface{}, userID interface{}) *MockCartRepository_GetCartByUserID_Call {
	return &MockCartRepository_GetCartByUserID_Call{Call: _e.mock.On("GetCartByUserID", ctx, userID)}
}

func (_c *MockCartRepository_GetCartByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockCartRepository_GetCartByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCartRepository_GetCartByUserID_Call) Return(_a0 []domain.CartItem, _a1 error) *MockCartRepository_GetCartByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCartRepository_GetCartByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]domain.CartItem, error)) *MockCartRepository_GetCartByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCartItem provides a mock function with given fields: ctx, userID, productID, quantity
func (_m *MockCartRepository) UpdateCartItem(ctx context.Context, userID uuid.UUID, productID uuid.UUID, quantity int) error {
	ret := _m.Called(ctx, userID, productID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCartItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int) error); ok {
		r0 = rf(ctx, userID, productID, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCartRepository_UpdateCartItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCartItem'
type MockCartRepository_UpdateCartItem_Call struct {
	*mock.Call
}

// UpdateCartItem is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - productID uuid.UUID
//   - quantity int
func (_e *MockCartRepository_Expecter) UpdateCartItem(ctx interface{}, userID interface{}, productID interface{}, quantity interface{}) *MockCartRepository_UpdateCartItem_Call {
	return &MockCartRepository_UpdateCartItem_Call{Call: _e.mock.On("UpdateCartItem", ctx, userID, productID, quantity)}
}

func (_c *MockCartRepository_UpdateCartItem_Call) Run(run func(ctx context.Context, userID uuid.UUID, productID uuid.UUID, quantity int)) *MockCartRepository_UpdateCartItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(int))
	})
	return _c
}

func (_c *MockCartRepository_UpdateCartItem_Call) Return(_a0 error) *MockCartRepository_UpdateCartItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCartRepository_UpdateCartItem_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, int) error) *MockCartRepository_UpdateCartItem_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertCartItem provides a mock function with given fields: ctx, item
func (_m *MockCartRepository) UpsertCartItem(ctx context.Context, item *domain.CartItem) error {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for UpsertCartItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CartItem) error); ok {
		r0 = rf(ctx, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCartRepository_UpsertCartItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertCartItem'
type MockCartRepository_UpsertCartItem_Call struct {
	*mock.Call
}

// UpsertCartItem is a helper method to define mock.On call
//   - ctx context.Context
//   - item *domain.CartItem
func (_e *MockCartRepository_Expecter) UpsertCartItem(ctx interface{}, item interface{}) *MockCartRepository_UpsertCartItem_Call {
	return &MockCartRepository_UpsertCartItem_Call{Call: _e.mock.On("UpsertCartItem", ctx, item)}
}

func (_c *MockCartRepository_UpsertCartItem_Call) Run(run func(ctx context.Context, item *domain.CartItem)) *MockCartRepository_UpsertCartItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.CartItem))
	})
	return _c
}

func (_c *MockCartRepository_UpsertCartItem_Call) Return(_a0 error) *MockCartRepository_UpsertCartItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCartRepository_UpsertCartItem_Call) RunAndReturn(run func(context.Context, *domain.CartItem) error) *MockCartRepository_UpsertCartItem_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCartRepository creates a new instance of MockCartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCartRepository {
	mock := &MockCartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
