// Code generated by mockery v2.53.6. DO NOT EDIT.

package cart

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockCartServiceInterface is an autogenerated mock type for the CartServiceInterface type
type MockCartServiceInterface struct {
	mock.Mock
}

type MockCartServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCartServiceInterface) EXPECT() *MockCartServiceInterface_Expecter {
	return &MockCartServiceInterface_Expecter{mock: &_m.Mock}
}

// AddToCart provides a mock function with given fields: ctx, userID, req
func (_m *MockCartServiceInterface) AddToCart(ctx context.Context, userID uuid.UUID, req AddToCartRequest) error {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for AddToCart")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, AddToCartRequest) error); ok {
		r0 = rf(ctx, userID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCartServiceInterface_AddToCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToCart'
type MockCartServiceInterface_AddToCart_Call struct {
	*mock.Call
}

// AddToCart is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req AddToCartRequest
func (_e *MockCartServiceInterface_Expecter) AddToCart(ctx interface{}, userID interface{}, req interface{}) *MockCartServiceInterface_AddToCart_Call {
	return &MockCartServiceInterface_AddToCart_Call{Call: _e.mock.On("AddToCart", ctx, userID, req)}
}

func (_c *MockCartServiceInterface_AddToCart_Call) Run(run func(ctx context.Context, userID uuid.UUID, req AddToCartRequest)) *MockCartServiceInterface_AddToCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(AddToCartRequest))
	})
	return _c
}

func (_c *MockCartServiceInterface_AddToCart_Call) Return(_a0 error) *MockCartServiceInterface_AddToCart_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCartServiceInterface_AddToCart_Call) RunAndReturn(run func(context.Context, uuid.UUID, AddToCartRequest) error) *MockCartServiceInterface_AddToCart_Call {
	_c.Call.Return(run)
	return _c
}

// ClearCart provides a mock function with given fields: ctx, userID
func (_m *MockCartServiceInterface) ClearCart(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ClearCart")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCartServiceInterface_ClearCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearCart'
type MockCartServiceInterface_ClearCart_Call struct {
	*mock.Call
}

// ClearCart is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockCartServiceInterface_Expecter) ClearCart(ctx interface{}, userID interface{}) *MockCartServiceInterface_ClearCart_Call {
	return &MockCartServiceInterface_ClearCart_Call{Call: _e.mock.On("ClearCart", ctx, userID)}
}

func (_c *MockCartServiceInterface_ClearCart_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockCartServiceInterface_ClearCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCartServiceInterface_ClearCart_Call) Return(_a0 error) *MockCartServiceInterface_ClearCart_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCartServiceInterface_ClearCart_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockCartServiceInterface_ClearCart_Call {
	_c.Call.Return(run)
	return _c
}

// GetCart provides a mock function with given fields: ctx, userID
func (_m *MockCartServiceInterface) GetCart(ctx context.Context, userID uuid.UUID) (*CartResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCart")
	}

	var r0 *CartResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*CartResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *CartResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CartResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCartServiceInterface_GetCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCart'
type MockCartServiceInterface_GetCart_Call struct {
	*mock.Call
}

// GetCart is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockCartServiceInterface_Expecter) GetCart(ctx interface{}, userID interface{}) *MockCartServiceInterface_GetCart_Call {
	return &MockCartServiceInterface_GetCart_Call{Call: _e.mock.On("GetCart", ctx, userID)}
}

func (_c *MockCartServiceInterface_GetCart_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockCartServiceInterface_GetCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCartServiceInterface_GetCart_Call) Return(_a0 *CartResponse, _a1 error) *MockCartServiceInterface_GetCart_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCartServiceInterface_GetCart_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*CartResponse, error)) *MockCartServiceInterface_GetCart_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveFromCart provides a mock function with given fields: ctx, userID, productID
func (_m *MockCartServiceInterface) RemoveFromCart(ctx context.Context, userID uuid.UUID, productID uuid.UUID) error {
	ret := _m.Called(ctx, userID, productID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFromCart")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, productID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCartServiceInterface_RemoveFromCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFromCart'
type MockCartServiceInterface_RemoveFromCart_Call struct {
	*mock.Call
}

// RemoveFromCart is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - productID uuid.UUID
func (_e *MockCartServiceInterface_Expecter) RemoveFromCart(ctx interface{}, userID interface{}, productID interface{}) *MockCartServiceInterface_RemoveFromCart_Call {
	return &MockCartServiceInterface_RemoveFromCart_Call{Call: _e.mock.On("RemoveFromCart", ctx, userID, productID)}
}

func (_c *MockCartServiceInterface_RemoveFromCart_Call) Run(run func(ctx context.Context, userID uuid.UUID, productID uuid.UUID)) *MockCartServiceInterface_RemoveFromCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockCartServiceInterface_RemoveFromCart_Call) Return(_a0 error) *MockCartServiceInterface_RemoveFromCart_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCartServiceInterface_RemoveFromCart_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockCartServiceInterface_RemoveFromCart_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCartItem provides a mock function with given fields: ctx, userID, productID, quantity
func (_m *MockCartServiceInterface) UpdateCartItem(ctx context.Context, userID uuid.UUID, productID uuid.UUID, quantity int) error {
	ret := _m.Called(ctx, userID, productID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCartItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int) error); ok {
		r0 = rf(ctx, userID, productID, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCartServiceInterface_UpdateCartItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCartItem'
type MockCartServiceInterface_UpdateCartItem_Call struct {
	*mock.Call
}

// UpdateCartItem is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - productID uuid.UUID
//   - quantity int
func (_e *MockCartServiceInterface_Expecter) UpdateCartItem(ctx interface{}, userID interface{}, productID interface{}, quantity interface{}) *MockCartServiceInterface_UpdateCartItem_Call {
	return &MockCartServiceInterface_UpdateCartItem_Call{Call: _e.mock.On("UpdateCartItem", ctx, userID, productID, quantity)}
}

func (_c *MockCartServiceInterface_UpdateCartItem_Call) Run(run func(ctx context.Context, userID uuid.UUID, productID uuid.UUID, quantity int)) *MockCartServiceInterface_UpdateCartItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(int))
	})
	return _c
}

func (_c *MockCartServiceInterface_UpdateCartItem_Call) Return(_a0 error) *MockCartServiceInterface_UpdateCartItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCartServiceInterface_UpdateCartItem_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, int) error) *MockCartServiceInterface_UpdateCartItem_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCartServiceInterface creates a new instance of MockCartServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCartServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCartServiceInterface {
	mock := &MockCartServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
