// Code generated by mockery v2.53.6. DO NOT EDIT.

package cart

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockCartService is an autogenerated mock type for the CartService type
type MockCartService struct {
	mock.Mock
}

type MockCartService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCartService) EXPECT() *MockCartService_Expecter {
	return &MockCartService_Expecter{mock: &_m.Mock}
}

// AddToCart provides a mock function with given fields: ctx, userID, req
func (_m *MockCartService) AddToCart(ctx context.Context, userID uuid.UUID, req AddToCartRequest) error {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for AddToCart")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, AddToCartRequest) error); ok {
		r0 = rf(ctx, userID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCartService_AddToCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToCart'
type MockCartService_AddToCart_Call struct {
	*mock.Call
}

// AddToCart is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req AddToCartRequest
func (_e *MockCartService_Expecter) AddToCart(ctx interface{}, userID interface{}, req interface{}) *MockCartService_AddToCart_Call {
	return &MockCartService_AddToCart_Call{Call: _e.mock.On("AddToCart", ctx, userID, req)}
}

func (_c *MockCartService_AddToCart_Call) Run(run func(ctx context.Context, userID uuid.UUID, req AddToCartRequest)) *MockCartService_AddToCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(AddToCartRequest))
	})
	return _c
}

func (_c *MockCartService_AddToCart_Call) Return(_a0 error) *MockCartService_AddToCart_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCartService_AddToCart_Call) RunAndReturn(run func(context.Context, uuid.UUID, AddToCartRequest) error) *MockCartService_AddToCart_Call {
	_c.Call.Return(run)
	return _c
}

// ClearCart provides a mock function with given fields: ctx, userID
func (_m *MockCartService) ClearCart(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ClearCart")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCartService_ClearCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearCart'
type MockCartService_ClearCart_Call struct {
	*mock.Call
}

// ClearCart is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockCartService_Expecter) ClearCart(ctx interface{}, userID interface{}) *MockCartService_ClearCart_Call {
	return &MockCartService_ClearCart_Call{Call: _e.mock.On("ClearCart", ctx, userID)}
}

func (_c *MockCartService_ClearCart_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockCartService_ClearCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCartService_ClearCart_Call) Return(_a0 error) *MockCartService_ClearCart_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCartService_ClearCart_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockCartService_ClearCart_Call {
	_c.Call.Return(run)
	return _c
}

// GetCart provides a mock function with given fields: ctx, userID
func (_m *MockCartService) GetCart(ctx context.Context, userID uuid.UUID) (*CartResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCart")
	}

	var r0 *CartResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*CartResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *CartResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CartResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCartService_GetCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCart'
type MockCartService_GetCart_Call struct {
	*mock.Call
}

// GetCart is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockCartService_Expecter) GetCart(ctx interface{}, userID interface{}) *MockCartService_GetCart_Call {
	return &MockCartService_GetCart_Call{Call: _e.mock.On("GetCart", ctx, userID)}
}

func (_c *MockCartService_GetCart_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockCartService_GetCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCartService_GetCart_Call) Return(_a0 *CartResponse, _a1 error) *MockCartService_GetCart_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCartService_GetCart_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*CartResponse, error)) *MockCartService_GetCart_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveFromCart provides a mock function with given fields: ctx, userID, productID
func (_m *MockCartService) RemoveFromCart(ctx context.Context, userID uuid.UUID, productID uuid.UUID) error {
	ret := _m.Called(ctx, userID, productID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFromCart")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, productID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCartService_RemoveFromCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFromCart'
type MockCartService_RemoveFromCart_Call struct {
	*mock.Call
}

// RemoveFromCart is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - productID uuid.UUID
func (_e *MockCartService_Expecter) RemoveFromCart(ctx interface{}, userID interface{}, productID interface{}) *MockCartService_RemoveFromCart_Call {
	return &MockCartService_RemoveFromCart_Call{Call: _e.mock.On("RemoveFromCart", ctx, userID, productID)}
}

func (_c *MockCartService_RemoveFromCart_Call) Run(run func(ctx context.Context, userID uuid.UUID, productID uuid.UUID)) *MockCartService_RemoveFromCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockCartService_RemoveFromCart_Call) Return(_a0 error) *MockCartService_RemoveFromCart_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCartService_RemoveFromCart_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockCartService_RemoveFromCart_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCartItem provides a mock function with given fields: ctx, userID, productID, quantity
func (_m *MockCartService) UpdateCartItem(ctx context.Context, userID uuid.UUID, productID uuid.UUID, quantity int) error {
	ret := _m.Called(ctx, userID, productID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCartItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int) error); ok {
		r0 = rf(ctx, userID, productID, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCartService_UpdateCartItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCartItem'
type MockCartService_UpdateCartItem_Call struct {
	*mock.Call
}

// UpdateCartItem is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - productID uuid.UUID
//   - quantity int
func (_e *MockCartService_Expecter) UpdateCartItem(ctx interface{}, userID interface{}, productID interface{}, quantity interface{}) *MockCartService_UpdateCartItem_Call {
	return &MockCartService_UpdateCartItem_Call{Call: _e.mock.On("UpdateCartItem", ctx, userID, productID, quantity)}
}

func (_c *MockCartService_UpdateCartItem_Call) Run(run func(ctx context.Context, userID uuid.UUID, productID uuid.UUID, quantity int)) *MockCartService_UpdateCartItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(int))
	})
	return _c
}

func (_c *MockCartService_UpdateCartItem_Call) Return(_a0 error) *MockCartService_UpdateCartItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCartService_UpdateCartItem_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, int) error) *MockCartService_UpdateCartItem_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCartService creates a new instance of MockCartService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCartService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCartService {
	mock := &MockCartService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
