// Code generated by mockery v2.53.6. DO NOT EDIT.

package cart

import (
	context "context"
	domain "go-marketplace/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockProductRepo is an autogenerated mock type for the ProductRepo type
type MockProductRepo struct {
	mock.Mock
}

type MockProductRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductRepo) EXPECT() *MockProductRepo_Expecter {
	return &MockProductRepo_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockProductRepo) GetByID(ctx context.Context, id uuid.UUID) (*domain.Product, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Product, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Product); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockProductRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockProductRepo_Expecter) GetByID(ctx interface{}, id interface{}) *MockProductRepo_GetByID_Call {
	return &MockProductRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockProductRepo_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockProductRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProductRepo_GetByID_Call) Return(_a0 *domain.Product, _a1 error) *MockProductRepo_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepo_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Product, error)) *MockProductRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductRepo creates a new instance of MockProductRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductRepo {
	mock := &MockProductRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
